//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CineVerCliente.EmpleadoServicio {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EmpleadoDTO", Namespace="http://schemas.datacontract.org/2004/07/CineVerServicios.DTO")]
    [System.SerializableAttribute()]
    public partial class EmpleadoDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ApellidosField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CalleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodigoPostalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] ContraseñaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool ContratadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CorreoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FechaNacimientoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] FotoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdEmpleadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdSucursalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MatriculaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombresField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NssField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NumeroCasaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NumeroTelefonoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RFCField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RolField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SexoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Apellidos {
            get {
                return this.ApellidosField;
            }
            set {
                if ((object.ReferenceEquals(this.ApellidosField, value) != true)) {
                    this.ApellidosField = value;
                    this.RaisePropertyChanged("Apellidos");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Calle {
            get {
                return this.CalleField;
            }
            set {
                if ((object.ReferenceEquals(this.CalleField, value) != true)) {
                    this.CalleField = value;
                    this.RaisePropertyChanged("Calle");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodigoPostal {
            get {
                return this.CodigoPostalField;
            }
            set {
                if ((object.ReferenceEquals(this.CodigoPostalField, value) != true)) {
                    this.CodigoPostalField = value;
                    this.RaisePropertyChanged("CodigoPostal");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] Contraseña {
            get {
                return this.ContraseñaField;
            }
            set {
                if ((object.ReferenceEquals(this.ContraseñaField, value) != true)) {
                    this.ContraseñaField = value;
                    this.RaisePropertyChanged("Contraseña");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Contratado {
            get {
                return this.ContratadoField;
            }
            set {
                if ((this.ContratadoField.Equals(value) != true)) {
                    this.ContratadoField = value;
                    this.RaisePropertyChanged("Contratado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Correo {
            get {
                return this.CorreoField;
            }
            set {
                if ((object.ReferenceEquals(this.CorreoField, value) != true)) {
                    this.CorreoField = value;
                    this.RaisePropertyChanged("Correo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FechaNacimiento {
            get {
                return this.FechaNacimientoField;
            }
            set {
                if ((this.FechaNacimientoField.Equals(value) != true)) {
                    this.FechaNacimientoField = value;
                    this.RaisePropertyChanged("FechaNacimiento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] Foto {
            get {
                return this.FotoField;
            }
            set {
                if ((object.ReferenceEquals(this.FotoField, value) != true)) {
                    this.FotoField = value;
                    this.RaisePropertyChanged("Foto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdEmpleado {
            get {
                return this.IdEmpleadoField;
            }
            set {
                if ((this.IdEmpleadoField.Equals(value) != true)) {
                    this.IdEmpleadoField = value;
                    this.RaisePropertyChanged("IdEmpleado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdSucursal {
            get {
                return this.IdSucursalField;
            }
            set {
                if ((this.IdSucursalField.Equals(value) != true)) {
                    this.IdSucursalField = value;
                    this.RaisePropertyChanged("IdSucursal");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Matricula {
            get {
                return this.MatriculaField;
            }
            set {
                if ((object.ReferenceEquals(this.MatriculaField, value) != true)) {
                    this.MatriculaField = value;
                    this.RaisePropertyChanged("Matricula");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombres {
            get {
                return this.NombresField;
            }
            set {
                if ((object.ReferenceEquals(this.NombresField, value) != true)) {
                    this.NombresField = value;
                    this.RaisePropertyChanged("Nombres");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nss {
            get {
                return this.NssField;
            }
            set {
                if ((object.ReferenceEquals(this.NssField, value) != true)) {
                    this.NssField = value;
                    this.RaisePropertyChanged("Nss");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NumeroCasa {
            get {
                return this.NumeroCasaField;
            }
            set {
                if ((object.ReferenceEquals(this.NumeroCasaField, value) != true)) {
                    this.NumeroCasaField = value;
                    this.RaisePropertyChanged("NumeroCasa");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NumeroTelefono {
            get {
                return this.NumeroTelefonoField;
            }
            set {
                if ((object.ReferenceEquals(this.NumeroTelefonoField, value) != true)) {
                    this.NumeroTelefonoField = value;
                    this.RaisePropertyChanged("NumeroTelefono");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RFC {
            get {
                return this.RFCField;
            }
            set {
                if ((object.ReferenceEquals(this.RFCField, value) != true)) {
                    this.RFCField = value;
                    this.RaisePropertyChanged("RFC");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Rol {
            get {
                return this.RolField;
            }
            set {
                if ((object.ReferenceEquals(this.RolField, value) != true)) {
                    this.RolField = value;
                    this.RaisePropertyChanged("Rol");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Sexo {
            get {
                return this.SexoField;
            }
            set {
                if ((object.ReferenceEquals(this.SexoField, value) != true)) {
                    this.SexoField = value;
                    this.RaisePropertyChanged("Sexo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResultDTO", Namespace="http://schemas.datacontract.org/2004/07/CineVerServicios.DTO")]
    [System.SerializableAttribute()]
    public partial class ResultDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ErrorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool EsExitosoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Error {
            get {
                return this.ErrorField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorField, value) != true)) {
                    this.ErrorField = value;
                    this.RaisePropertyChanged("Error");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool EsExitoso {
            get {
                return this.EsExitosoField;
            }
            set {
                if ((this.EsExitosoField.Equals(value) != true)) {
                    this.EsExitosoField = value;
                    this.RaisePropertyChanged("EsExitoso");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ListaEmpleadosDTO", Namespace="http://schemas.datacontract.org/2004/07/CineVerServicios.DTO")]
    [System.SerializableAttribute()]
    public partial class ListaEmpleadosDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private CineVerCliente.EmpleadoServicio.EmpleadoDTO[] EmpleadosField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private CineVerCliente.EmpleadoServicio.ResultDTO ResultField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CineVerCliente.EmpleadoServicio.EmpleadoDTO[] Empleados {
            get {
                return this.EmpleadosField;
            }
            set {
                if ((object.ReferenceEquals(this.EmpleadosField, value) != true)) {
                    this.EmpleadosField = value;
                    this.RaisePropertyChanged("Empleados");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CineVerCliente.EmpleadoServicio.ResultDTO Result {
            get {
                return this.ResultField;
            }
            set {
                if ((object.ReferenceEquals(this.ResultField, value) != true)) {
                    this.ResultField = value;
                    this.RaisePropertyChanged("Result");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EmpleadoResponseDTO", Namespace="http://schemas.datacontract.org/2004/07/CineVerServicios.DTO")]
    [System.SerializableAttribute()]
    public partial class EmpleadoResponseDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private CineVerCliente.EmpleadoServicio.ResultDTO ResultDTOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private CineVerCliente.EmpleadoServicio.EmpleadoDTO empleadoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CineVerCliente.EmpleadoServicio.ResultDTO ResultDTO {
            get {
                return this.ResultDTOField;
            }
            set {
                if ((object.ReferenceEquals(this.ResultDTOField, value) != true)) {
                    this.ResultDTOField = value;
                    this.RaisePropertyChanged("ResultDTO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CineVerCliente.EmpleadoServicio.EmpleadoDTO empleado {
            get {
                return this.empleadoField;
            }
            set {
                if ((object.ReferenceEquals(this.empleadoField, value) != true)) {
                    this.empleadoField = value;
                    this.RaisePropertyChanged("empleado");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="EmpleadoServicio.IEmpleadoServicio")]
    public interface IEmpleadoServicio {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmpleadoServicio/RegistrarEmpleado", ReplyAction="http://tempuri.org/IEmpleadoServicio/RegistrarEmpleadoResponse")]
        CineVerCliente.EmpleadoServicio.ResultDTO RegistrarEmpleado(CineVerCliente.EmpleadoServicio.EmpleadoDTO empleadoDTO);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmpleadoServicio/RegistrarEmpleado", ReplyAction="http://tempuri.org/IEmpleadoServicio/RegistrarEmpleadoResponse")]
        System.Threading.Tasks.Task<CineVerCliente.EmpleadoServicio.ResultDTO> RegistrarEmpleadoAsync(CineVerCliente.EmpleadoServicio.EmpleadoDTO empleadoDTO);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmpleadoServicio/ModificarEmpleado", ReplyAction="http://tempuri.org/IEmpleadoServicio/ModificarEmpleadoResponse")]
        CineVerCliente.EmpleadoServicio.ResultDTO ModificarEmpleado(CineVerCliente.EmpleadoServicio.EmpleadoDTO empleadoDTO);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmpleadoServicio/ModificarEmpleado", ReplyAction="http://tempuri.org/IEmpleadoServicio/ModificarEmpleadoResponse")]
        System.Threading.Tasks.Task<CineVerCliente.EmpleadoServicio.ResultDTO> ModificarEmpleadoAsync(CineVerCliente.EmpleadoServicio.EmpleadoDTO empleadoDTO);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmpleadoServicio/InhabilitarEmpleado", ReplyAction="http://tempuri.org/IEmpleadoServicio/InhabilitarEmpleadoResponse")]
        CineVerCliente.EmpleadoServicio.ResultDTO InhabilitarEmpleado(int idEmpleado);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmpleadoServicio/InhabilitarEmpleado", ReplyAction="http://tempuri.org/IEmpleadoServicio/InhabilitarEmpleadoResponse")]
        System.Threading.Tasks.Task<CineVerCliente.EmpleadoServicio.ResultDTO> InhabilitarEmpleadoAsync(int idEmpleado);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmpleadoServicio/ObtenerEmpleados", ReplyAction="http://tempuri.org/IEmpleadoServicio/ObtenerEmpleadosResponse")]
        CineVerCliente.EmpleadoServicio.ListaEmpleadosDTO ObtenerEmpleados();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmpleadoServicio/ObtenerEmpleados", ReplyAction="http://tempuri.org/IEmpleadoServicio/ObtenerEmpleadosResponse")]
        System.Threading.Tasks.Task<CineVerCliente.EmpleadoServicio.ListaEmpleadosDTO> ObtenerEmpleadosAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmpleadoServicio/BuscarEmpleadoPorMatricula", ReplyAction="http://tempuri.org/IEmpleadoServicio/BuscarEmpleadoPorMatriculaResponse")]
        CineVerCliente.EmpleadoServicio.EmpleadoResponseDTO BuscarEmpleadoPorMatricula(string matricula);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmpleadoServicio/BuscarEmpleadoPorMatricula", ReplyAction="http://tempuri.org/IEmpleadoServicio/BuscarEmpleadoPorMatriculaResponse")]
        System.Threading.Tasks.Task<CineVerCliente.EmpleadoServicio.EmpleadoResponseDTO> BuscarEmpleadoPorMatriculaAsync(string matricula);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmpleadoServicio/ExisteEmpleado", ReplyAction="http://tempuri.org/IEmpleadoServicio/ExisteEmpleadoResponse")]
        CineVerCliente.EmpleadoServicio.ResultDTO ExisteEmpleado(string matriucla);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmpleadoServicio/ExisteEmpleado", ReplyAction="http://tempuri.org/IEmpleadoServicio/ExisteEmpleadoResponse")]
        System.Threading.Tasks.Task<CineVerCliente.EmpleadoServicio.ResultDTO> ExisteEmpleadoAsync(string matriucla);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmpleadoServicio/VerificarInicioSesion", ReplyAction="http://tempuri.org/IEmpleadoServicio/VerificarInicioSesionResponse")]
        CineVerCliente.EmpleadoServicio.ResultDTO VerificarInicioSesion(string matricula, string contrasena);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmpleadoServicio/VerificarInicioSesion", ReplyAction="http://tempuri.org/IEmpleadoServicio/VerificarInicioSesionResponse")]
        System.Threading.Tasks.Task<CineVerCliente.EmpleadoServicio.ResultDTO> VerificarInicioSesionAsync(string matricula, string contrasena);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IEmpleadoServicioChannel : CineVerCliente.EmpleadoServicio.IEmpleadoServicio, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class EmpleadoServicioClient : System.ServiceModel.ClientBase<CineVerCliente.EmpleadoServicio.IEmpleadoServicio>, CineVerCliente.EmpleadoServicio.IEmpleadoServicio {
        
        public EmpleadoServicioClient() {
        }
        
        public EmpleadoServicioClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public EmpleadoServicioClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EmpleadoServicioClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EmpleadoServicioClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public CineVerCliente.EmpleadoServicio.ResultDTO RegistrarEmpleado(CineVerCliente.EmpleadoServicio.EmpleadoDTO empleadoDTO) {
            return base.Channel.RegistrarEmpleado(empleadoDTO);
        }
        
        public System.Threading.Tasks.Task<CineVerCliente.EmpleadoServicio.ResultDTO> RegistrarEmpleadoAsync(CineVerCliente.EmpleadoServicio.EmpleadoDTO empleadoDTO) {
            return base.Channel.RegistrarEmpleadoAsync(empleadoDTO);
        }
        
        public CineVerCliente.EmpleadoServicio.ResultDTO ModificarEmpleado(CineVerCliente.EmpleadoServicio.EmpleadoDTO empleadoDTO) {
            return base.Channel.ModificarEmpleado(empleadoDTO);
        }
        
        public System.Threading.Tasks.Task<CineVerCliente.EmpleadoServicio.ResultDTO> ModificarEmpleadoAsync(CineVerCliente.EmpleadoServicio.EmpleadoDTO empleadoDTO) {
            return base.Channel.ModificarEmpleadoAsync(empleadoDTO);
        }
        
        public CineVerCliente.EmpleadoServicio.ResultDTO InhabilitarEmpleado(int idEmpleado) {
            return base.Channel.InhabilitarEmpleado(idEmpleado);
        }
        
        public System.Threading.Tasks.Task<CineVerCliente.EmpleadoServicio.ResultDTO> InhabilitarEmpleadoAsync(int idEmpleado) {
            return base.Channel.InhabilitarEmpleadoAsync(idEmpleado);
        }
        
        public CineVerCliente.EmpleadoServicio.ListaEmpleadosDTO ObtenerEmpleados() {
            return base.Channel.ObtenerEmpleados();
        }
        
        public System.Threading.Tasks.Task<CineVerCliente.EmpleadoServicio.ListaEmpleadosDTO> ObtenerEmpleadosAsync() {
            return base.Channel.ObtenerEmpleadosAsync();
        }
        
        public CineVerCliente.EmpleadoServicio.EmpleadoResponseDTO BuscarEmpleadoPorMatricula(string matricula) {
            return base.Channel.BuscarEmpleadoPorMatricula(matricula);
        }
        
        public System.Threading.Tasks.Task<CineVerCliente.EmpleadoServicio.EmpleadoResponseDTO> BuscarEmpleadoPorMatriculaAsync(string matricula) {
            return base.Channel.BuscarEmpleadoPorMatriculaAsync(matricula);
        }
        
        public CineVerCliente.EmpleadoServicio.ResultDTO ExisteEmpleado(string matriucla) {
            return base.Channel.ExisteEmpleado(matriucla);
        }
        
        public System.Threading.Tasks.Task<CineVerCliente.EmpleadoServicio.ResultDTO> ExisteEmpleadoAsync(string matriucla) {
            return base.Channel.ExisteEmpleadoAsync(matriucla);
        }
        
        public CineVerCliente.EmpleadoServicio.ResultDTO VerificarInicioSesion(string matricula, string contrasena) {
            return base.Channel.VerificarInicioSesion(matricula, contrasena);
        }
        
        public System.Threading.Tasks.Task<CineVerCliente.EmpleadoServicio.ResultDTO> VerificarInicioSesionAsync(string matricula, string contrasena) {
            return base.Channel.VerificarInicioSesionAsync(matricula, contrasena);
        }
    }
}
