//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CineVerCliente.CuentaFidelidadServicio {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CuentaFidelidadDTO", Namespace="http://schemas.datacontract.org/2004/07/CineVerServicios.DTO")]
    [System.SerializableAttribute()]
    public partial class CuentaFidelidadDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdCuentaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdSocioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PuntosField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdCuenta {
            get {
                return this.IdCuentaField;
            }
            set {
                if ((this.IdCuentaField.Equals(value) != true)) {
                    this.IdCuentaField = value;
                    this.RaisePropertyChanged("IdCuenta");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdSocio {
            get {
                return this.IdSocioField;
            }
            set {
                if ((this.IdSocioField.Equals(value) != true)) {
                    this.IdSocioField = value;
                    this.RaisePropertyChanged("IdSocio");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Puntos {
            get {
                return this.PuntosField;
            }
            set {
                if ((this.PuntosField.Equals(value) != true)) {
                    this.PuntosField = value;
                    this.RaisePropertyChanged("Puntos");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResultDTO", Namespace="http://schemas.datacontract.org/2004/07/CineVerServicios.DTO")]
    [System.SerializableAttribute()]
    public partial class ResultDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ErrorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool EsExitosoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Error {
            get {
                return this.ErrorField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorField, value) != true)) {
                    this.ErrorField = value;
                    this.RaisePropertyChanged("Error");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool EsExitoso {
            get {
                return this.EsExitosoField;
            }
            set {
                if ((this.EsExitosoField.Equals(value) != true)) {
                    this.EsExitosoField = value;
                    this.RaisePropertyChanged("EsExitoso");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CuentaFidelidadResponseDTO", Namespace="http://schemas.datacontract.org/2004/07/CineVerServicios.DTO")]
    [System.SerializableAttribute()]
    public partial class CuentaFidelidadResponseDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private CineVerCliente.CuentaFidelidadServicio.ResultDTO ResultDTOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private CineVerCliente.CuentaFidelidadServicio.CuentaFidelidadDTO cuentaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CineVerCliente.CuentaFidelidadServicio.ResultDTO ResultDTO {
            get {
                return this.ResultDTOField;
            }
            set {
                if ((object.ReferenceEquals(this.ResultDTOField, value) != true)) {
                    this.ResultDTOField = value;
                    this.RaisePropertyChanged("ResultDTO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CineVerCliente.CuentaFidelidadServicio.CuentaFidelidadDTO cuenta {
            get {
                return this.cuentaField;
            }
            set {
                if ((object.ReferenceEquals(this.cuentaField, value) != true)) {
                    this.cuentaField = value;
                    this.RaisePropertyChanged("cuenta");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CuentaFidelidadServicio.ICuentaFidelidadServicio")]
    public interface ICuentaFidelidadServicio {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICuentaFidelidadServicio/RegistrarCuentaFidelidad", ReplyAction="http://tempuri.org/ICuentaFidelidadServicio/RegistrarCuentaFidelidadResponse")]
        CineVerCliente.CuentaFidelidadServicio.ResultDTO RegistrarCuentaFidelidad(CineVerCliente.CuentaFidelidadServicio.CuentaFidelidadDTO cuentaFidelidadDTO);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICuentaFidelidadServicio/RegistrarCuentaFidelidad", ReplyAction="http://tempuri.org/ICuentaFidelidadServicio/RegistrarCuentaFidelidadResponse")]
        System.Threading.Tasks.Task<CineVerCliente.CuentaFidelidadServicio.ResultDTO> RegistrarCuentaFidelidadAsync(CineVerCliente.CuentaFidelidadServicio.CuentaFidelidadDTO cuentaFidelidadDTO);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICuentaFidelidadServicio/ObtenerCuentaFidelidadPorIdSocio", ReplyAction="http://tempuri.org/ICuentaFidelidadServicio/ObtenerCuentaFidelidadPorIdSocioRespo" +
            "nse")]
        CineVerCliente.CuentaFidelidadServicio.CuentaFidelidadResponseDTO ObtenerCuentaFidelidadPorIdSocio(int idSocio);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICuentaFidelidadServicio/ObtenerCuentaFidelidadPorIdSocio", ReplyAction="http://tempuri.org/ICuentaFidelidadServicio/ObtenerCuentaFidelidadPorIdSocioRespo" +
            "nse")]
        System.Threading.Tasks.Task<CineVerCliente.CuentaFidelidadServicio.CuentaFidelidadResponseDTO> ObtenerCuentaFidelidadPorIdSocioAsync(int idSocio);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICuentaFidelidadServicio/ModificarCuentaFidelidad", ReplyAction="http://tempuri.org/ICuentaFidelidadServicio/ModificarCuentaFidelidadResponse")]
        CineVerCliente.CuentaFidelidadServicio.ResultDTO ModificarCuentaFidelidad(CineVerCliente.CuentaFidelidadServicio.CuentaFidelidadDTO cuentaFidelidadDTO);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICuentaFidelidadServicio/ModificarCuentaFidelidad", ReplyAction="http://tempuri.org/ICuentaFidelidadServicio/ModificarCuentaFidelidadResponse")]
        System.Threading.Tasks.Task<CineVerCliente.CuentaFidelidadServicio.ResultDTO> ModificarCuentaFidelidadAsync(CineVerCliente.CuentaFidelidadServicio.CuentaFidelidadDTO cuentaFidelidadDTO);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICuentaFidelidadServicio/InhabilitarCuentaFidelidad", ReplyAction="http://tempuri.org/ICuentaFidelidadServicio/InhabilitarCuentaFidelidadResponse")]
        CineVerCliente.CuentaFidelidadServicio.ResultDTO InhabilitarCuentaFidelidad(int idSocio);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICuentaFidelidadServicio/InhabilitarCuentaFidelidad", ReplyAction="http://tempuri.org/ICuentaFidelidadServicio/InhabilitarCuentaFidelidadResponse")]
        System.Threading.Tasks.Task<CineVerCliente.CuentaFidelidadServicio.ResultDTO> InhabilitarCuentaFidelidadAsync(int idSocio);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICuentaFidelidadServicioChannel : CineVerCliente.CuentaFidelidadServicio.ICuentaFidelidadServicio, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CuentaFidelidadServicioClient : System.ServiceModel.ClientBase<CineVerCliente.CuentaFidelidadServicio.ICuentaFidelidadServicio>, CineVerCliente.CuentaFidelidadServicio.ICuentaFidelidadServicio {
        
        public CuentaFidelidadServicioClient() {
        }
        
        public CuentaFidelidadServicioClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CuentaFidelidadServicioClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CuentaFidelidadServicioClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CuentaFidelidadServicioClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public CineVerCliente.CuentaFidelidadServicio.ResultDTO RegistrarCuentaFidelidad(CineVerCliente.CuentaFidelidadServicio.CuentaFidelidadDTO cuentaFidelidadDTO) {
            return base.Channel.RegistrarCuentaFidelidad(cuentaFidelidadDTO);
        }
        
        public System.Threading.Tasks.Task<CineVerCliente.CuentaFidelidadServicio.ResultDTO> RegistrarCuentaFidelidadAsync(CineVerCliente.CuentaFidelidadServicio.CuentaFidelidadDTO cuentaFidelidadDTO) {
            return base.Channel.RegistrarCuentaFidelidadAsync(cuentaFidelidadDTO);
        }
        
        public CineVerCliente.CuentaFidelidadServicio.CuentaFidelidadResponseDTO ObtenerCuentaFidelidadPorIdSocio(int idSocio) {
            return base.Channel.ObtenerCuentaFidelidadPorIdSocio(idSocio);
        }
        
        public System.Threading.Tasks.Task<CineVerCliente.CuentaFidelidadServicio.CuentaFidelidadResponseDTO> ObtenerCuentaFidelidadPorIdSocioAsync(int idSocio) {
            return base.Channel.ObtenerCuentaFidelidadPorIdSocioAsync(idSocio);
        }
        
        public CineVerCliente.CuentaFidelidadServicio.ResultDTO ModificarCuentaFidelidad(CineVerCliente.CuentaFidelidadServicio.CuentaFidelidadDTO cuentaFidelidadDTO) {
            return base.Channel.ModificarCuentaFidelidad(cuentaFidelidadDTO);
        }
        
        public System.Threading.Tasks.Task<CineVerCliente.CuentaFidelidadServicio.ResultDTO> ModificarCuentaFidelidadAsync(CineVerCliente.CuentaFidelidadServicio.CuentaFidelidadDTO cuentaFidelidadDTO) {
            return base.Channel.ModificarCuentaFidelidadAsync(cuentaFidelidadDTO);
        }
        
        public CineVerCliente.CuentaFidelidadServicio.ResultDTO InhabilitarCuentaFidelidad(int idSocio) {
            return base.Channel.InhabilitarCuentaFidelidad(idSocio);
        }
        
        public System.Threading.Tasks.Task<CineVerCliente.CuentaFidelidadServicio.ResultDTO> InhabilitarCuentaFidelidadAsync(int idSocio) {
            return base.Channel.InhabilitarCuentaFidelidadAsync(idSocio);
        }
    }
}
