//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CineVerCliente.VentaServicio {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="VentaDTO", Namespace="http://schemas.datacontract.org/2004/07/CineVerServicios.DTO")]
    [System.SerializableAttribute()]
    public partial class VentaDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FechaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FolioVentaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdEmpleadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdSocioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdSucursalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdVentaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MetodoPagoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TIpoVentaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal TotalField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Fecha {
            get {
                return this.FechaField;
            }
            set {
                if ((this.FechaField.Equals(value) != true)) {
                    this.FechaField = value;
                    this.RaisePropertyChanged("Fecha");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FolioVenta {
            get {
                return this.FolioVentaField;
            }
            set {
                if ((object.ReferenceEquals(this.FolioVentaField, value) != true)) {
                    this.FolioVentaField = value;
                    this.RaisePropertyChanged("FolioVenta");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdEmpleado {
            get {
                return this.IdEmpleadoField;
            }
            set {
                if ((this.IdEmpleadoField.Equals(value) != true)) {
                    this.IdEmpleadoField = value;
                    this.RaisePropertyChanged("IdEmpleado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdSocio {
            get {
                return this.IdSocioField;
            }
            set {
                if ((this.IdSocioField.Equals(value) != true)) {
                    this.IdSocioField = value;
                    this.RaisePropertyChanged("IdSocio");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdSucursal {
            get {
                return this.IdSucursalField;
            }
            set {
                if ((this.IdSucursalField.Equals(value) != true)) {
                    this.IdSucursalField = value;
                    this.RaisePropertyChanged("IdSucursal");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdVenta {
            get {
                return this.IdVentaField;
            }
            set {
                if ((this.IdVentaField.Equals(value) != true)) {
                    this.IdVentaField = value;
                    this.RaisePropertyChanged("IdVenta");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MetodoPago {
            get {
                return this.MetodoPagoField;
            }
            set {
                if ((object.ReferenceEquals(this.MetodoPagoField, value) != true)) {
                    this.MetodoPagoField = value;
                    this.RaisePropertyChanged("MetodoPago");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TIpoVenta {
            get {
                return this.TIpoVentaField;
            }
            set {
                if ((object.ReferenceEquals(this.TIpoVentaField, value) != true)) {
                    this.TIpoVentaField = value;
                    this.RaisePropertyChanged("TIpoVenta");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Total {
            get {
                return this.TotalField;
            }
            set {
                if ((this.TotalField.Equals(value) != true)) {
                    this.TotalField = value;
                    this.RaisePropertyChanged("Total");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResultDTO", Namespace="http://schemas.datacontract.org/2004/07/CineVerServicios.DTO")]
    [System.SerializableAttribute()]
    public partial class ResultDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ErrorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool EsExitosoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Error {
            get {
                return this.ErrorField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorField, value) != true)) {
                    this.ErrorField = value;
                    this.RaisePropertyChanged("Error");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool EsExitoso {
            get {
                return this.EsExitosoField;
            }
            set {
                if ((this.EsExitosoField.Equals(value) != true)) {
                    this.EsExitosoField = value;
                    this.RaisePropertyChanged("EsExitoso");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ListaPromocionesDTO", Namespace="http://schemas.datacontract.org/2004/07/CineVerServicios.DTO")]
    [System.SerializableAttribute()]
    public partial class ListaPromocionesDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private CineVerCliente.VentaServicio.PromocionDTO[] PromocionesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private CineVerCliente.VentaServicio.ResultDTO ResultField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CineVerCliente.VentaServicio.PromocionDTO[] Promociones {
            get {
                return this.PromocionesField;
            }
            set {
                if ((object.ReferenceEquals(this.PromocionesField, value) != true)) {
                    this.PromocionesField = value;
                    this.RaisePropertyChanged("Promociones");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CineVerCliente.VentaServicio.ResultDTO Result {
            get {
                return this.ResultField;
            }
            set {
                if ((object.ReferenceEquals(this.ResultField, value) != true)) {
                    this.ResultField = value;
                    this.RaisePropertyChanged("Result");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PromocionDTO", Namespace="http://schemas.datacontract.org/2004/07/CineVerServicios.DTO")]
    [System.SerializableAttribute()]
    public partial class PromocionDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool DomingoAplicaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdPromocionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdSucursalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool JuevesAplicaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool LunesAplicaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool MartesAplicaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool MiercolesAplicaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int NumeroProductosNecesariosField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int NumeroProductosPagarField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProductoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool SabadoAplicaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TipoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool ViernesAplicaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool DomingoAplica {
            get {
                return this.DomingoAplicaField;
            }
            set {
                if ((this.DomingoAplicaField.Equals(value) != true)) {
                    this.DomingoAplicaField = value;
                    this.RaisePropertyChanged("DomingoAplica");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdPromocion {
            get {
                return this.IdPromocionField;
            }
            set {
                if ((this.IdPromocionField.Equals(value) != true)) {
                    this.IdPromocionField = value;
                    this.RaisePropertyChanged("IdPromocion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdSucursal {
            get {
                return this.IdSucursalField;
            }
            set {
                if ((this.IdSucursalField.Equals(value) != true)) {
                    this.IdSucursalField = value;
                    this.RaisePropertyChanged("IdSucursal");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool JuevesAplica {
            get {
                return this.JuevesAplicaField;
            }
            set {
                if ((this.JuevesAplicaField.Equals(value) != true)) {
                    this.JuevesAplicaField = value;
                    this.RaisePropertyChanged("JuevesAplica");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool LunesAplica {
            get {
                return this.LunesAplicaField;
            }
            set {
                if ((this.LunesAplicaField.Equals(value) != true)) {
                    this.LunesAplicaField = value;
                    this.RaisePropertyChanged("LunesAplica");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool MartesAplica {
            get {
                return this.MartesAplicaField;
            }
            set {
                if ((this.MartesAplicaField.Equals(value) != true)) {
                    this.MartesAplicaField = value;
                    this.RaisePropertyChanged("MartesAplica");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool MiercolesAplica {
            get {
                return this.MiercolesAplicaField;
            }
            set {
                if ((this.MiercolesAplicaField.Equals(value) != true)) {
                    this.MiercolesAplicaField = value;
                    this.RaisePropertyChanged("MiercolesAplica");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int NumeroProductosNecesarios {
            get {
                return this.NumeroProductosNecesariosField;
            }
            set {
                if ((this.NumeroProductosNecesariosField.Equals(value) != true)) {
                    this.NumeroProductosNecesariosField = value;
                    this.RaisePropertyChanged("NumeroProductosNecesarios");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int NumeroProductosPagar {
            get {
                return this.NumeroProductosPagarField;
            }
            set {
                if ((this.NumeroProductosPagarField.Equals(value) != true)) {
                    this.NumeroProductosPagarField = value;
                    this.RaisePropertyChanged("NumeroProductosPagar");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Producto {
            get {
                return this.ProductoField;
            }
            set {
                if ((object.ReferenceEquals(this.ProductoField, value) != true)) {
                    this.ProductoField = value;
                    this.RaisePropertyChanged("Producto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool SabadoAplica {
            get {
                return this.SabadoAplicaField;
            }
            set {
                if ((this.SabadoAplicaField.Equals(value) != true)) {
                    this.SabadoAplicaField = value;
                    this.RaisePropertyChanged("SabadoAplica");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Tipo {
            get {
                return this.TipoField;
            }
            set {
                if ((object.ReferenceEquals(this.TipoField, value) != true)) {
                    this.TipoField = value;
                    this.RaisePropertyChanged("Tipo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool ViernesAplica {
            get {
                return this.ViernesAplicaField;
            }
            set {
                if ((this.ViernesAplicaField.Equals(value) != true)) {
                    this.ViernesAplicaField = value;
                    this.RaisePropertyChanged("ViernesAplica");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ListaVentasDTO", Namespace="http://schemas.datacontract.org/2004/07/CineVerServicios.DTO")]
    [System.SerializableAttribute()]
    public partial class ListaVentasDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private CineVerCliente.VentaServicio.ResultDTO ResultField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private CineVerCliente.VentaServicio.VentaDTO[] VentasField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CineVerCliente.VentaServicio.ResultDTO Result {
            get {
                return this.ResultField;
            }
            set {
                if ((object.ReferenceEquals(this.ResultField, value) != true)) {
                    this.ResultField = value;
                    this.RaisePropertyChanged("Result");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CineVerCliente.VentaServicio.VentaDTO[] Ventas {
            get {
                return this.VentasField;
            }
            set {
                if ((object.ReferenceEquals(this.VentasField, value) != true)) {
                    this.VentasField = value;
                    this.RaisePropertyChanged("Ventas");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="VentaTipoResponseDTO", Namespace="http://schemas.datacontract.org/2004/07/CineVerServicios.DTO")]
    [System.SerializableAttribute()]
    public partial class VentaTipoResponseDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private CineVerCliente.VentaServicio.ResultDTO ResultDTOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal TotalField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CineVerCliente.VentaServicio.ResultDTO ResultDTO {
            get {
                return this.ResultDTOField;
            }
            set {
                if ((object.ReferenceEquals(this.ResultDTOField, value) != true)) {
                    this.ResultDTOField = value;
                    this.RaisePropertyChanged("ResultDTO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Total {
            get {
                return this.TotalField;
            }
            set {
                if ((this.TotalField.Equals(value) != true)) {
                    this.TotalField = value;
                    this.RaisePropertyChanged("Total");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="VentaServicio.IVentaServicio")]
    public interface IVentaServicio {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVentaServicio/RealizarPagoDulceria", ReplyAction="http://tempuri.org/IVentaServicio/RealizarPagoDulceriaResponse")]
        CineVerCliente.VentaServicio.ResultDTO RealizarPagoDulceria(CineVerCliente.VentaServicio.VentaDTO venta, System.Collections.Generic.Dictionary<int, int> productos, double puntosUsados);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVentaServicio/RealizarPagoDulceria", ReplyAction="http://tempuri.org/IVentaServicio/RealizarPagoDulceriaResponse")]
        System.Threading.Tasks.Task<CineVerCliente.VentaServicio.ResultDTO> RealizarPagoDulceriaAsync(CineVerCliente.VentaServicio.VentaDTO venta, System.Collections.Generic.Dictionary<int, int> productos, double puntosUsados);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVentaServicio/RealizarPagoBoletos", ReplyAction="http://tempuri.org/IVentaServicio/RealizarPagoBoletosResponse")]
        CineVerCliente.VentaServicio.ResultDTO RealizarPagoBoletos(CineVerCliente.VentaServicio.VentaDTO venta, int[] asientosIds, double puntosUsados);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVentaServicio/RealizarPagoBoletos", ReplyAction="http://tempuri.org/IVentaServicio/RealizarPagoBoletosResponse")]
        System.Threading.Tasks.Task<CineVerCliente.VentaServicio.ResultDTO> RealizarPagoBoletosAsync(CineVerCliente.VentaServicio.VentaDTO venta, int[] asientosIds, double puntosUsados);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVentaServicio/ObtenerPromociones", ReplyAction="http://tempuri.org/IVentaServicio/ObtenerPromocionesResponse")]
        CineVerCliente.VentaServicio.ListaPromocionesDTO ObtenerPromociones(int idSucursal);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVentaServicio/ObtenerPromociones", ReplyAction="http://tempuri.org/IVentaServicio/ObtenerPromocionesResponse")]
        System.Threading.Tasks.Task<CineVerCliente.VentaServicio.ListaPromocionesDTO> ObtenerPromocionesAsync(int idSucursal);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVentaServicio/ObtenerPromocionesDulceria", ReplyAction="http://tempuri.org/IVentaServicio/ObtenerPromocionesDulceriaResponse")]
        CineVerCliente.VentaServicio.ListaPromocionesDTO ObtenerPromocionesDulceria(int idSucursal);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVentaServicio/ObtenerPromocionesDulceria", ReplyAction="http://tempuri.org/IVentaServicio/ObtenerPromocionesDulceriaResponse")]
        System.Threading.Tasks.Task<CineVerCliente.VentaServicio.ListaPromocionesDTO> ObtenerPromocionesDulceriaAsync(int idSucursal);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVentaServicio/ObtenerPromocionesBoletos", ReplyAction="http://tempuri.org/IVentaServicio/ObtenerPromocionesBoletosResponse")]
        CineVerCliente.VentaServicio.ListaPromocionesDTO ObtenerPromocionesBoletos(int idSucursal);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVentaServicio/ObtenerPromocionesBoletos", ReplyAction="http://tempuri.org/IVentaServicio/ObtenerPromocionesBoletosResponse")]
        System.Threading.Tasks.Task<CineVerCliente.VentaServicio.ListaPromocionesDTO> ObtenerPromocionesBoletosAsync(int idSucursal);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVentaServicio/ActualizarPromocion", ReplyAction="http://tempuri.org/IVentaServicio/ActualizarPromocionResponse")]
        CineVerCliente.VentaServicio.ResultDTO ActualizarPromocion(CineVerCliente.VentaServicio.PromocionDTO promocion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVentaServicio/ActualizarPromocion", ReplyAction="http://tempuri.org/IVentaServicio/ActualizarPromocionResponse")]
        System.Threading.Tasks.Task<CineVerCliente.VentaServicio.ResultDTO> ActualizarPromocionAsync(CineVerCliente.VentaServicio.PromocionDTO promocion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVentaServicio/RegistrarPromocion", ReplyAction="http://tempuri.org/IVentaServicio/RegistrarPromocionResponse")]
        CineVerCliente.VentaServicio.ResultDTO RegistrarPromocion(CineVerCliente.VentaServicio.PromocionDTO promocion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVentaServicio/RegistrarPromocion", ReplyAction="http://tempuri.org/IVentaServicio/RegistrarPromocionResponse")]
        System.Threading.Tasks.Task<CineVerCliente.VentaServicio.ResultDTO> RegistrarPromocionAsync(CineVerCliente.VentaServicio.PromocionDTO promocion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVentaServicio/ObtenerVentasPorAnio", ReplyAction="http://tempuri.org/IVentaServicio/ObtenerVentasPorAnioResponse")]
        CineVerCliente.VentaServicio.ListaVentasDTO ObtenerVentasPorAnio(int anio, int idSucursal);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVentaServicio/ObtenerVentasPorAnio", ReplyAction="http://tempuri.org/IVentaServicio/ObtenerVentasPorAnioResponse")]
        System.Threading.Tasks.Task<CineVerCliente.VentaServicio.ListaVentasDTO> ObtenerVentasPorAnioAsync(int anio, int idSucursal);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVentaServicio/ObtenerVentasPorMes", ReplyAction="http://tempuri.org/IVentaServicio/ObtenerVentasPorMesResponse")]
        CineVerCliente.VentaServicio.ListaVentasDTO ObtenerVentasPorMes(int mes, int anio, int idSucursal);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVentaServicio/ObtenerVentasPorMes", ReplyAction="http://tempuri.org/IVentaServicio/ObtenerVentasPorMesResponse")]
        System.Threading.Tasks.Task<CineVerCliente.VentaServicio.ListaVentasDTO> ObtenerVentasPorMesAsync(int mes, int anio, int idSucursal);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVentaServicio/ObtenerVentaPorFolio", ReplyAction="http://tempuri.org/IVentaServicio/ObtenerVentaPorFolioResponse")]
        CineVerCliente.VentaServicio.ResultDTO ObtenerVentaPorFolio(string folio);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVentaServicio/ObtenerVentaPorFolio", ReplyAction="http://tempuri.org/IVentaServicio/ObtenerVentaPorFolioResponse")]
        System.Threading.Tasks.Task<CineVerCliente.VentaServicio.ResultDTO> ObtenerVentaPorFolioAsync(string folio);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVentaServicio/VerificarFechaVentaParaDevolucion", ReplyAction="http://tempuri.org/IVentaServicio/VerificarFechaVentaParaDevolucionResponse")]
        CineVerCliente.VentaServicio.ResultDTO VerificarFechaVentaParaDevolucion(string folio);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVentaServicio/VerificarFechaVentaParaDevolucion", ReplyAction="http://tempuri.org/IVentaServicio/VerificarFechaVentaParaDevolucionResponse")]
        System.Threading.Tasks.Task<CineVerCliente.VentaServicio.ResultDTO> VerificarFechaVentaParaDevolucionAsync(string folio);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVentaServicio/ObtenerVentasDeBoletosDelDia", ReplyAction="http://tempuri.org/IVentaServicio/ObtenerVentasDeBoletosDelDiaResponse")]
        CineVerCliente.VentaServicio.VentaTipoResponseDTO ObtenerVentasDeBoletosDelDia(int idSucursal);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVentaServicio/ObtenerVentasDeBoletosDelDia", ReplyAction="http://tempuri.org/IVentaServicio/ObtenerVentasDeBoletosDelDiaResponse")]
        System.Threading.Tasks.Task<CineVerCliente.VentaServicio.VentaTipoResponseDTO> ObtenerVentasDeBoletosDelDiaAsync(int idSucursal);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVentaServicio/ObtenerVentasDeDulceriaDelDia", ReplyAction="http://tempuri.org/IVentaServicio/ObtenerVentasDeDulceriaDelDiaResponse")]
        CineVerCliente.VentaServicio.VentaTipoResponseDTO ObtenerVentasDeDulceriaDelDia(int idSucursal);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVentaServicio/ObtenerVentasDeDulceriaDelDia", ReplyAction="http://tempuri.org/IVentaServicio/ObtenerVentasDeDulceriaDelDiaResponse")]
        System.Threading.Tasks.Task<CineVerCliente.VentaServicio.VentaTipoResponseDTO> ObtenerVentasDeDulceriaDelDiaAsync(int idSucursal);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVentaServicio/ObtenerVentasEnEfectivoDelDia", ReplyAction="http://tempuri.org/IVentaServicio/ObtenerVentasEnEfectivoDelDiaResponse")]
        CineVerCliente.VentaServicio.VentaTipoResponseDTO ObtenerVentasEnEfectivoDelDia(int idSucursal);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVentaServicio/ObtenerVentasEnEfectivoDelDia", ReplyAction="http://tempuri.org/IVentaServicio/ObtenerVentasEnEfectivoDelDiaResponse")]
        System.Threading.Tasks.Task<CineVerCliente.VentaServicio.VentaTipoResponseDTO> ObtenerVentasEnEfectivoDelDiaAsync(int idSucursal);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IVentaServicioChannel : CineVerCliente.VentaServicio.IVentaServicio, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class VentaServicioClient : System.ServiceModel.ClientBase<CineVerCliente.VentaServicio.IVentaServicio>, CineVerCliente.VentaServicio.IVentaServicio {
        
        public VentaServicioClient() {
        }
        
        public VentaServicioClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public VentaServicioClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public VentaServicioClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public VentaServicioClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public CineVerCliente.VentaServicio.ResultDTO RealizarPagoDulceria(CineVerCliente.VentaServicio.VentaDTO venta, System.Collections.Generic.Dictionary<int, int> productos, double puntosUsados) {
            return base.Channel.RealizarPagoDulceria(venta, productos, puntosUsados);
        }
        
        public System.Threading.Tasks.Task<CineVerCliente.VentaServicio.ResultDTO> RealizarPagoDulceriaAsync(CineVerCliente.VentaServicio.VentaDTO venta, System.Collections.Generic.Dictionary<int, int> productos, double puntosUsados) {
            return base.Channel.RealizarPagoDulceriaAsync(venta, productos, puntosUsados);
        }
        
        public CineVerCliente.VentaServicio.ResultDTO RealizarPagoBoletos(CineVerCliente.VentaServicio.VentaDTO venta, int[] asientosIds, double puntosUsados) {
            return base.Channel.RealizarPagoBoletos(venta, asientosIds, puntosUsados);
        }
        
        public System.Threading.Tasks.Task<CineVerCliente.VentaServicio.ResultDTO> RealizarPagoBoletosAsync(CineVerCliente.VentaServicio.VentaDTO venta, int[] asientosIds, double puntosUsados) {
            return base.Channel.RealizarPagoBoletosAsync(venta, asientosIds, puntosUsados);
        }
        
        public CineVerCliente.VentaServicio.ListaPromocionesDTO ObtenerPromociones(int idSucursal) {
            return base.Channel.ObtenerPromociones(idSucursal);
        }
        
        public System.Threading.Tasks.Task<CineVerCliente.VentaServicio.ListaPromocionesDTO> ObtenerPromocionesAsync(int idSucursal) {
            return base.Channel.ObtenerPromocionesAsync(idSucursal);
        }
        
        public CineVerCliente.VentaServicio.ListaPromocionesDTO ObtenerPromocionesDulceria(int idSucursal) {
            return base.Channel.ObtenerPromocionesDulceria(idSucursal);
        }
        
        public System.Threading.Tasks.Task<CineVerCliente.VentaServicio.ListaPromocionesDTO> ObtenerPromocionesDulceriaAsync(int idSucursal) {
            return base.Channel.ObtenerPromocionesDulceriaAsync(idSucursal);
        }
        
        public CineVerCliente.VentaServicio.ListaPromocionesDTO ObtenerPromocionesBoletos(int idSucursal) {
            return base.Channel.ObtenerPromocionesBoletos(idSucursal);
        }
        
        public System.Threading.Tasks.Task<CineVerCliente.VentaServicio.ListaPromocionesDTO> ObtenerPromocionesBoletosAsync(int idSucursal) {
            return base.Channel.ObtenerPromocionesBoletosAsync(idSucursal);
        }
        
        public CineVerCliente.VentaServicio.ResultDTO ActualizarPromocion(CineVerCliente.VentaServicio.PromocionDTO promocion) {
            return base.Channel.ActualizarPromocion(promocion);
        }
        
        public System.Threading.Tasks.Task<CineVerCliente.VentaServicio.ResultDTO> ActualizarPromocionAsync(CineVerCliente.VentaServicio.PromocionDTO promocion) {
            return base.Channel.ActualizarPromocionAsync(promocion);
        }
        
        public CineVerCliente.VentaServicio.ResultDTO RegistrarPromocion(CineVerCliente.VentaServicio.PromocionDTO promocion) {
            return base.Channel.RegistrarPromocion(promocion);
        }
        
        public System.Threading.Tasks.Task<CineVerCliente.VentaServicio.ResultDTO> RegistrarPromocionAsync(CineVerCliente.VentaServicio.PromocionDTO promocion) {
            return base.Channel.RegistrarPromocionAsync(promocion);
        }
        
        public CineVerCliente.VentaServicio.ListaVentasDTO ObtenerVentasPorAnio(int anio, int idSucursal) {
            return base.Channel.ObtenerVentasPorAnio(anio, idSucursal);
        }
        
        public System.Threading.Tasks.Task<CineVerCliente.VentaServicio.ListaVentasDTO> ObtenerVentasPorAnioAsync(int anio, int idSucursal) {
            return base.Channel.ObtenerVentasPorAnioAsync(anio, idSucursal);
        }
        
        public CineVerCliente.VentaServicio.ListaVentasDTO ObtenerVentasPorMes(int mes, int anio, int idSucursal) {
            return base.Channel.ObtenerVentasPorMes(mes, anio, idSucursal);
        }
        
        public System.Threading.Tasks.Task<CineVerCliente.VentaServicio.ListaVentasDTO> ObtenerVentasPorMesAsync(int mes, int anio, int idSucursal) {
            return base.Channel.ObtenerVentasPorMesAsync(mes, anio, idSucursal);
        }
        
        public CineVerCliente.VentaServicio.ResultDTO ObtenerVentaPorFolio(string folio) {
            return base.Channel.ObtenerVentaPorFolio(folio);
        }
        
        public System.Threading.Tasks.Task<CineVerCliente.VentaServicio.ResultDTO> ObtenerVentaPorFolioAsync(string folio) {
            return base.Channel.ObtenerVentaPorFolioAsync(folio);
        }
        
        public CineVerCliente.VentaServicio.ResultDTO VerificarFechaVentaParaDevolucion(string folio) {
            return base.Channel.VerificarFechaVentaParaDevolucion(folio);
        }
        
        public System.Threading.Tasks.Task<CineVerCliente.VentaServicio.ResultDTO> VerificarFechaVentaParaDevolucionAsync(string folio) {
            return base.Channel.VerificarFechaVentaParaDevolucionAsync(folio);
        }
        
        public CineVerCliente.VentaServicio.VentaTipoResponseDTO ObtenerVentasDeBoletosDelDia(int idSucursal) {
            return base.Channel.ObtenerVentasDeBoletosDelDia(idSucursal);
        }
        
        public System.Threading.Tasks.Task<CineVerCliente.VentaServicio.VentaTipoResponseDTO> ObtenerVentasDeBoletosDelDiaAsync(int idSucursal) {
            return base.Channel.ObtenerVentasDeBoletosDelDiaAsync(idSucursal);
        }
        
        public CineVerCliente.VentaServicio.VentaTipoResponseDTO ObtenerVentasDeDulceriaDelDia(int idSucursal) {
            return base.Channel.ObtenerVentasDeDulceriaDelDia(idSucursal);
        }
        
        public System.Threading.Tasks.Task<CineVerCliente.VentaServicio.VentaTipoResponseDTO> ObtenerVentasDeDulceriaDelDiaAsync(int idSucursal) {
            return base.Channel.ObtenerVentasDeDulceriaDelDiaAsync(idSucursal);
        }
        
        public CineVerCliente.VentaServicio.VentaTipoResponseDTO ObtenerVentasEnEfectivoDelDia(int idSucursal) {
            return base.Channel.ObtenerVentasEnEfectivoDelDia(idSucursal);
        }
        
        public System.Threading.Tasks.Task<CineVerCliente.VentaServicio.VentaTipoResponseDTO> ObtenerVentasEnEfectivoDelDiaAsync(int idSucursal) {
            return base.Channel.ObtenerVentasEnEfectivoDelDiaAsync(idSucursal);
        }
    }
}
