//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CineVerCliente.CorteCajaServicio {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CorteCajaDTO", Namespace="http://schemas.datacontract.org/2004/07/CineVerServicios.DTO")]
    [System.SerializableAttribute()]
    public partial class CorteCajaDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal DiferenciaEfectivoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal EfectivoCajaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal EfectivoEsperadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FechaCorteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal GananciasField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal GastosField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdCorteCajaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdSucursalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal InicioDiaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal VentaTotalField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal DiferenciaEfectivo {
            get {
                return this.DiferenciaEfectivoField;
            }
            set {
                if ((this.DiferenciaEfectivoField.Equals(value) != true)) {
                    this.DiferenciaEfectivoField = value;
                    this.RaisePropertyChanged("DiferenciaEfectivo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal EfectivoCaja {
            get {
                return this.EfectivoCajaField;
            }
            set {
                if ((this.EfectivoCajaField.Equals(value) != true)) {
                    this.EfectivoCajaField = value;
                    this.RaisePropertyChanged("EfectivoCaja");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal EfectivoEsperado {
            get {
                return this.EfectivoEsperadoField;
            }
            set {
                if ((this.EfectivoEsperadoField.Equals(value) != true)) {
                    this.EfectivoEsperadoField = value;
                    this.RaisePropertyChanged("EfectivoEsperado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FechaCorte {
            get {
                return this.FechaCorteField;
            }
            set {
                if ((this.FechaCorteField.Equals(value) != true)) {
                    this.FechaCorteField = value;
                    this.RaisePropertyChanged("FechaCorte");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Ganancias {
            get {
                return this.GananciasField;
            }
            set {
                if ((this.GananciasField.Equals(value) != true)) {
                    this.GananciasField = value;
                    this.RaisePropertyChanged("Ganancias");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Gastos {
            get {
                return this.GastosField;
            }
            set {
                if ((this.GastosField.Equals(value) != true)) {
                    this.GastosField = value;
                    this.RaisePropertyChanged("Gastos");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdCorteCaja {
            get {
                return this.IdCorteCajaField;
            }
            set {
                if ((this.IdCorteCajaField.Equals(value) != true)) {
                    this.IdCorteCajaField = value;
                    this.RaisePropertyChanged("IdCorteCaja");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdSucursal {
            get {
                return this.IdSucursalField;
            }
            set {
                if ((this.IdSucursalField.Equals(value) != true)) {
                    this.IdSucursalField = value;
                    this.RaisePropertyChanged("IdSucursal");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal InicioDia {
            get {
                return this.InicioDiaField;
            }
            set {
                if ((this.InicioDiaField.Equals(value) != true)) {
                    this.InicioDiaField = value;
                    this.RaisePropertyChanged("InicioDia");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal VentaTotal {
            get {
                return this.VentaTotalField;
            }
            set {
                if ((this.VentaTotalField.Equals(value) != true)) {
                    this.VentaTotalField = value;
                    this.RaisePropertyChanged("VentaTotal");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResultDTO", Namespace="http://schemas.datacontract.org/2004/07/CineVerServicios.DTO")]
    [System.SerializableAttribute()]
    public partial class ResultDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ErrorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool EsExitosoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Error {
            get {
                return this.ErrorField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorField, value) != true)) {
                    this.ErrorField = value;
                    this.RaisePropertyChanged("Error");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool EsExitoso {
            get {
                return this.EsExitosoField;
            }
            set {
                if ((this.EsExitosoField.Equals(value) != true)) {
                    this.EsExitosoField = value;
                    this.RaisePropertyChanged("EsExitoso");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CorteCajaResponseDTO", Namespace="http://schemas.datacontract.org/2004/07/CineVerServicios.DTO")]
    [System.SerializableAttribute()]
    public partial class CorteCajaResponseDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal MontoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private CineVerCliente.CorteCajaServicio.ResultDTO ResultDTOField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Monto {
            get {
                return this.MontoField;
            }
            set {
                if ((this.MontoField.Equals(value) != true)) {
                    this.MontoField = value;
                    this.RaisePropertyChanged("Monto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CineVerCliente.CorteCajaServicio.ResultDTO ResultDTO {
            get {
                return this.ResultDTOField;
            }
            set {
                if ((object.ReferenceEquals(this.ResultDTOField, value) != true)) {
                    this.ResultDTOField = value;
                    this.RaisePropertyChanged("ResultDTO");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CorteCajaServicio.ICorteCajaServicio")]
    public interface ICorteCajaServicio {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICorteCajaServicio/GuardarCorteCaja", ReplyAction="http://tempuri.org/ICorteCajaServicio/GuardarCorteCajaResponse")]
        CineVerCliente.CorteCajaServicio.ResultDTO GuardarCorteCaja(CineVerCliente.CorteCajaServicio.CorteCajaDTO corteCajaDTO);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICorteCajaServicio/GuardarCorteCaja", ReplyAction="http://tempuri.org/ICorteCajaServicio/GuardarCorteCajaResponse")]
        System.Threading.Tasks.Task<CineVerCliente.CorteCajaServicio.ResultDTO> GuardarCorteCajaAsync(CineVerCliente.CorteCajaServicio.CorteCajaDTO corteCajaDTO);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICorteCajaServicio/ObtenerMontoInicioDia", ReplyAction="http://tempuri.org/ICorteCajaServicio/ObtenerMontoInicioDiaResponse")]
        CineVerCliente.CorteCajaServicio.CorteCajaResponseDTO ObtenerMontoInicioDia(int idSucursal);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICorteCajaServicio/ObtenerMontoInicioDia", ReplyAction="http://tempuri.org/ICorteCajaServicio/ObtenerMontoInicioDiaResponse")]
        System.Threading.Tasks.Task<CineVerCliente.CorteCajaServicio.CorteCajaResponseDTO> ObtenerMontoInicioDiaAsync(int idSucursal);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICorteCajaServicioChannel : CineVerCliente.CorteCajaServicio.ICorteCajaServicio, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CorteCajaServicioClient : System.ServiceModel.ClientBase<CineVerCliente.CorteCajaServicio.ICorteCajaServicio>, CineVerCliente.CorteCajaServicio.ICorteCajaServicio {
        
        public CorteCajaServicioClient() {
        }
        
        public CorteCajaServicioClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CorteCajaServicioClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CorteCajaServicioClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CorteCajaServicioClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public CineVerCliente.CorteCajaServicio.ResultDTO GuardarCorteCaja(CineVerCliente.CorteCajaServicio.CorteCajaDTO corteCajaDTO) {
            return base.Channel.GuardarCorteCaja(corteCajaDTO);
        }
        
        public System.Threading.Tasks.Task<CineVerCliente.CorteCajaServicio.ResultDTO> GuardarCorteCajaAsync(CineVerCliente.CorteCajaServicio.CorteCajaDTO corteCajaDTO) {
            return base.Channel.GuardarCorteCajaAsync(corteCajaDTO);
        }
        
        public CineVerCliente.CorteCajaServicio.CorteCajaResponseDTO ObtenerMontoInicioDia(int idSucursal) {
            return base.Channel.ObtenerMontoInicioDia(idSucursal);
        }
        
        public System.Threading.Tasks.Task<CineVerCliente.CorteCajaServicio.CorteCajaResponseDTO> ObtenerMontoInicioDiaAsync(int idSucursal) {
            return base.Channel.ObtenerMontoInicioDiaAsync(idSucursal);
        }
    }
}
