//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CineVerCliente.FuncionServicio {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ListaFuncionesDTO", Namespace="http://schemas.datacontract.org/2004/07/CineVerServicios.DTO")]
    [System.SerializableAttribute()]
    public partial class ListaFuncionesDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private CineVerCliente.FuncionServicio.FuncionDTO[] funcionesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private CineVerCliente.FuncionServicio.ResultDTO resultField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CineVerCliente.FuncionServicio.FuncionDTO[] funciones {
            get {
                return this.funcionesField;
            }
            set {
                if ((object.ReferenceEquals(this.funcionesField, value) != true)) {
                    this.funcionesField = value;
                    this.RaisePropertyChanged("funciones");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CineVerCliente.FuncionServicio.ResultDTO result {
            get {
                return this.resultField;
            }
            set {
                if ((object.ReferenceEquals(this.resultField, value) != true)) {
                    this.resultField = value;
                    this.RaisePropertyChanged("result");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResultDTO", Namespace="http://schemas.datacontract.org/2004/07/CineVerServicios.DTO")]
    [System.SerializableAttribute()]
    public partial class ResultDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ErrorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool EsExitosoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Error {
            get {
                return this.ErrorField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorField, value) != true)) {
                    this.ErrorField = value;
                    this.RaisePropertyChanged("Error");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool EsExitoso {
            get {
                return this.EsExitosoField;
            }
            set {
                if ((this.EsExitosoField.Equals(value) != true)) {
                    this.EsExitosoField = value;
                    this.RaisePropertyChanged("EsExitoso");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FuncionDTO", Namespace="http://schemas.datacontract.org/2004/07/CineVerServicios.DTO")]
    [System.SerializableAttribute()]
    public partial class FuncionDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private CineVerCliente.FuncionServicio.PeliculaDTOs PelículaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private CineVerCliente.FuncionServicio.SalaDTO SalaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> fechaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.TimeSpan> horaInicioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idFuncionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> idPeliculaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> idSalaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> precioBoletoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CineVerCliente.FuncionServicio.PeliculaDTOs Película {
            get {
                return this.PelículaField;
            }
            set {
                if ((object.ReferenceEquals(this.PelículaField, value) != true)) {
                    this.PelículaField = value;
                    this.RaisePropertyChanged("Película");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CineVerCliente.FuncionServicio.SalaDTO Sala {
            get {
                return this.SalaField;
            }
            set {
                if ((object.ReferenceEquals(this.SalaField, value) != true)) {
                    this.SalaField = value;
                    this.RaisePropertyChanged("Sala");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> fecha {
            get {
                return this.fechaField;
            }
            set {
                if ((this.fechaField.Equals(value) != true)) {
                    this.fechaField = value;
                    this.RaisePropertyChanged("fecha");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.TimeSpan> horaInicio {
            get {
                return this.horaInicioField;
            }
            set {
                if ((this.horaInicioField.Equals(value) != true)) {
                    this.horaInicioField = value;
                    this.RaisePropertyChanged("horaInicio");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idFuncion {
            get {
                return this.idFuncionField;
            }
            set {
                if ((this.idFuncionField.Equals(value) != true)) {
                    this.idFuncionField = value;
                    this.RaisePropertyChanged("idFuncion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> idPelicula {
            get {
                return this.idPeliculaField;
            }
            set {
                if ((this.idPeliculaField.Equals(value) != true)) {
                    this.idPeliculaField = value;
                    this.RaisePropertyChanged("idPelicula");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> idSala {
            get {
                return this.idSalaField;
            }
            set {
                if ((this.idSalaField.Equals(value) != true)) {
                    this.idSalaField = value;
                    this.RaisePropertyChanged("idSala");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> precioBoleto {
            get {
                return this.precioBoletoField;
            }
            set {
                if ((this.precioBoletoField.Equals(value) != true)) {
                    this.precioBoletoField = value;
                    this.RaisePropertyChanged("precioBoleto");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PeliculaDTOs", Namespace="http://schemas.datacontract.org/2004/07/CineVerServicios.DTO")]
    [System.SerializableAttribute()]
    public partial class PeliculaDTOs : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string directorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.TimeSpan> duracionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string generoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idPeliculaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> idSucursalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] posterField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string sinopsisField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string director {
            get {
                return this.directorField;
            }
            set {
                if ((object.ReferenceEquals(this.directorField, value) != true)) {
                    this.directorField = value;
                    this.RaisePropertyChanged("director");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.TimeSpan> duracion {
            get {
                return this.duracionField;
            }
            set {
                if ((this.duracionField.Equals(value) != true)) {
                    this.duracionField = value;
                    this.RaisePropertyChanged("duracion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string genero {
            get {
                return this.generoField;
            }
            set {
                if ((object.ReferenceEquals(this.generoField, value) != true)) {
                    this.generoField = value;
                    this.RaisePropertyChanged("genero");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idPelicula {
            get {
                return this.idPeliculaField;
            }
            set {
                if ((this.idPeliculaField.Equals(value) != true)) {
                    this.idPeliculaField = value;
                    this.RaisePropertyChanged("idPelicula");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> idSucursal {
            get {
                return this.idSucursalField;
            }
            set {
                if ((this.idSucursalField.Equals(value) != true)) {
                    this.idSucursalField = value;
                    this.RaisePropertyChanged("idSucursal");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                if ((object.ReferenceEquals(this.nombreField, value) != true)) {
                    this.nombreField = value;
                    this.RaisePropertyChanged("nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] poster {
            get {
                return this.posterField;
            }
            set {
                if ((object.ReferenceEquals(this.posterField, value) != true)) {
                    this.posterField = value;
                    this.RaisePropertyChanged("poster");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string sinopsis {
            get {
                return this.sinopsisField;
            }
            set {
                if ((object.ReferenceEquals(this.sinopsisField, value) != true)) {
                    this.sinopsisField = value;
                    this.RaisePropertyChanged("sinopsis");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SalaDTO", Namespace="http://schemas.datacontract.org/2004/07/CineVerServicios.DTO")]
    [System.SerializableAttribute()]
    public partial class SalaDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string descripcionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string estadoSalaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idSalaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> idSucursalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> numeroFilasField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string descripcion {
            get {
                return this.descripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.descripcionField, value) != true)) {
                    this.descripcionField = value;
                    this.RaisePropertyChanged("descripcion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string estadoSala {
            get {
                return this.estadoSalaField;
            }
            set {
                if ((object.ReferenceEquals(this.estadoSalaField, value) != true)) {
                    this.estadoSalaField = value;
                    this.RaisePropertyChanged("estadoSala");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idSala {
            get {
                return this.idSalaField;
            }
            set {
                if ((this.idSalaField.Equals(value) != true)) {
                    this.idSalaField = value;
                    this.RaisePropertyChanged("idSala");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> idSucursal {
            get {
                return this.idSucursalField;
            }
            set {
                if ((this.idSucursalField.Equals(value) != true)) {
                    this.idSucursalField = value;
                    this.RaisePropertyChanged("idSucursal");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                if ((object.ReferenceEquals(this.nombreField, value) != true)) {
                    this.nombreField = value;
                    this.RaisePropertyChanged("nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> numeroFilas {
            get {
                return this.numeroFilasField;
            }
            set {
                if ((this.numeroFilasField.Equals(value) != true)) {
                    this.numeroFilasField = value;
                    this.RaisePropertyChanged("numeroFilas");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="FuncionServicio.IFuncionServicio")]
    public interface IFuncionServicio {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFuncionServicio/ObtenerFuncionesPorPeliculaYFecha", ReplyAction="http://tempuri.org/IFuncionServicio/ObtenerFuncionesPorPeliculaYFechaResponse")]
        CineVerCliente.FuncionServicio.ListaFuncionesDTO ObtenerFuncionesPorPeliculaYFecha(int idPelicula, System.DateTime fecha);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFuncionServicio/ObtenerFuncionesPorPeliculaYFecha", ReplyAction="http://tempuri.org/IFuncionServicio/ObtenerFuncionesPorPeliculaYFechaResponse")]
        System.Threading.Tasks.Task<CineVerCliente.FuncionServicio.ListaFuncionesDTO> ObtenerFuncionesPorPeliculaYFechaAsync(int idPelicula, System.DateTime fecha);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFuncionServicio/ObtenerFuncionesPorFecha", ReplyAction="http://tempuri.org/IFuncionServicio/ObtenerFuncionesPorFechaResponse")]
        CineVerCliente.FuncionServicio.ListaFuncionesDTO ObtenerFuncionesPorFecha(System.DateTime fecha);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFuncionServicio/ObtenerFuncionesPorFecha", ReplyAction="http://tempuri.org/IFuncionServicio/ObtenerFuncionesPorFechaResponse")]
        System.Threading.Tasks.Task<CineVerCliente.FuncionServicio.ListaFuncionesDTO> ObtenerFuncionesPorFechaAsync(System.DateTime fecha);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFuncionServicio/ObtenerFuncionesPorFechaYSala", ReplyAction="http://tempuri.org/IFuncionServicio/ObtenerFuncionesPorFechaYSalaResponse")]
        CineVerCliente.FuncionServicio.ListaFuncionesDTO ObtenerFuncionesPorFechaYSala(int idSala, System.DateTime fecha);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFuncionServicio/ObtenerFuncionesPorFechaYSala", ReplyAction="http://tempuri.org/IFuncionServicio/ObtenerFuncionesPorFechaYSalaResponse")]
        System.Threading.Tasks.Task<CineVerCliente.FuncionServicio.ListaFuncionesDTO> ObtenerFuncionesPorFechaYSalaAsync(int idSala, System.DateTime fecha);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFuncionServicio/AgregarFuncion", ReplyAction="http://tempuri.org/IFuncionServicio/AgregarFuncionResponse")]
        string AgregarFuncion(CineVerCliente.FuncionServicio.FuncionDTO funcion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFuncionServicio/AgregarFuncion", ReplyAction="http://tempuri.org/IFuncionServicio/AgregarFuncionResponse")]
        System.Threading.Tasks.Task<string> AgregarFuncionAsync(CineVerCliente.FuncionServicio.FuncionDTO funcion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFuncionServicio/EditarFUncion", ReplyAction="http://tempuri.org/IFuncionServicio/EditarFUncionResponse")]
        string EditarFUncion(CineVerCliente.FuncionServicio.FuncionDTO funcionOriginal, CineVerCliente.FuncionServicio.FuncionDTO funcionEditada);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFuncionServicio/EditarFUncion", ReplyAction="http://tempuri.org/IFuncionServicio/EditarFUncionResponse")]
        System.Threading.Tasks.Task<string> EditarFUncionAsync(CineVerCliente.FuncionServicio.FuncionDTO funcionOriginal, CineVerCliente.FuncionServicio.FuncionDTO funcionEditada);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFuncionServicio/EliminarFuncion", ReplyAction="http://tempuri.org/IFuncionServicio/EliminarFuncionResponse")]
        string EliminarFuncion(CineVerCliente.FuncionServicio.FuncionDTO funcion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFuncionServicio/EliminarFuncion", ReplyAction="http://tempuri.org/IFuncionServicio/EliminarFuncionResponse")]
        System.Threading.Tasks.Task<string> EliminarFuncionAsync(CineVerCliente.FuncionServicio.FuncionDTO funcion);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IFuncionServicioChannel : CineVerCliente.FuncionServicio.IFuncionServicio, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class FuncionServicioClient : System.ServiceModel.ClientBase<CineVerCliente.FuncionServicio.IFuncionServicio>, CineVerCliente.FuncionServicio.IFuncionServicio {
        
        public FuncionServicioClient() {
        }
        
        public FuncionServicioClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public FuncionServicioClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FuncionServicioClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FuncionServicioClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public CineVerCliente.FuncionServicio.ListaFuncionesDTO ObtenerFuncionesPorPeliculaYFecha(int idPelicula, System.DateTime fecha) {
            return base.Channel.ObtenerFuncionesPorPeliculaYFecha(idPelicula, fecha);
        }
        
        public System.Threading.Tasks.Task<CineVerCliente.FuncionServicio.ListaFuncionesDTO> ObtenerFuncionesPorPeliculaYFechaAsync(int idPelicula, System.DateTime fecha) {
            return base.Channel.ObtenerFuncionesPorPeliculaYFechaAsync(idPelicula, fecha);
        }
        
        public CineVerCliente.FuncionServicio.ListaFuncionesDTO ObtenerFuncionesPorFecha(System.DateTime fecha) {
            return base.Channel.ObtenerFuncionesPorFecha(fecha);
        }
        
        public System.Threading.Tasks.Task<CineVerCliente.FuncionServicio.ListaFuncionesDTO> ObtenerFuncionesPorFechaAsync(System.DateTime fecha) {
            return base.Channel.ObtenerFuncionesPorFechaAsync(fecha);
        }
        
        public CineVerCliente.FuncionServicio.ListaFuncionesDTO ObtenerFuncionesPorFechaYSala(int idSala, System.DateTime fecha) {
            return base.Channel.ObtenerFuncionesPorFechaYSala(idSala, fecha);
        }
        
        public System.Threading.Tasks.Task<CineVerCliente.FuncionServicio.ListaFuncionesDTO> ObtenerFuncionesPorFechaYSalaAsync(int idSala, System.DateTime fecha) {
            return base.Channel.ObtenerFuncionesPorFechaYSalaAsync(idSala, fecha);
        }
        
        public string AgregarFuncion(CineVerCliente.FuncionServicio.FuncionDTO funcion) {
            return base.Channel.AgregarFuncion(funcion);
        }
        
        public System.Threading.Tasks.Task<string> AgregarFuncionAsync(CineVerCliente.FuncionServicio.FuncionDTO funcion) {
            return base.Channel.AgregarFuncionAsync(funcion);
        }
        
        public string EditarFUncion(CineVerCliente.FuncionServicio.FuncionDTO funcionOriginal, CineVerCliente.FuncionServicio.FuncionDTO funcionEditada) {
            return base.Channel.EditarFUncion(funcionOriginal, funcionEditada);
        }
        
        public System.Threading.Tasks.Task<string> EditarFUncionAsync(CineVerCliente.FuncionServicio.FuncionDTO funcionOriginal, CineVerCliente.FuncionServicio.FuncionDTO funcionEditada) {
            return base.Channel.EditarFUncionAsync(funcionOriginal, funcionEditada);
        }
        
        public string EliminarFuncion(CineVerCliente.FuncionServicio.FuncionDTO funcion) {
            return base.Channel.EliminarFuncion(funcion);
        }
        
        public System.Threading.Tasks.Task<string> EliminarFuncionAsync(CineVerCliente.FuncionServicio.FuncionDTO funcion) {
            return base.Channel.EliminarFuncionAsync(funcion);
        }
    }
}
