//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CineVerCliente.FilaServicio {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FilaDTO", Namespace="http://schemas.datacontract.org/2004/07/CineVerServicios.DTO")]
    [System.SerializableAttribute()]
    public partial class FilaDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idFilaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> idSalaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> numeroAsientosField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> númeroFilaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idFila {
            get {
                return this.idFilaField;
            }
            set {
                if ((this.idFilaField.Equals(value) != true)) {
                    this.idFilaField = value;
                    this.RaisePropertyChanged("idFila");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> idSala {
            get {
                return this.idSalaField;
            }
            set {
                if ((this.idSalaField.Equals(value) != true)) {
                    this.idSalaField = value;
                    this.RaisePropertyChanged("idSala");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> numeroAsientos {
            get {
                return this.numeroAsientosField;
            }
            set {
                if ((this.numeroAsientosField.Equals(value) != true)) {
                    this.numeroAsientosField = value;
                    this.RaisePropertyChanged("numeroAsientos");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> númeroFila {
            get {
                return this.númeroFilaField;
            }
            set {
                if ((this.númeroFilaField.Equals(value) != true)) {
                    this.númeroFilaField = value;
                    this.RaisePropertyChanged("númeroFila");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ListaFilasDTO", Namespace="http://schemas.datacontract.org/2004/07/CineVerServicios.DTO")]
    [System.SerializableAttribute()]
    public partial class ListaFilasDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private CineVerCliente.FilaServicio.FilaDTO[] FilasField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private CineVerCliente.FilaServicio.ResultDTO ResultField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CineVerCliente.FilaServicio.FilaDTO[] Filas {
            get {
                return this.FilasField;
            }
            set {
                if ((object.ReferenceEquals(this.FilasField, value) != true)) {
                    this.FilasField = value;
                    this.RaisePropertyChanged("Filas");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CineVerCliente.FilaServicio.ResultDTO Result {
            get {
                return this.ResultField;
            }
            set {
                if ((object.ReferenceEquals(this.ResultField, value) != true)) {
                    this.ResultField = value;
                    this.RaisePropertyChanged("Result");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResultDTO", Namespace="http://schemas.datacontract.org/2004/07/CineVerServicios.DTO")]
    [System.SerializableAttribute()]
    public partial class ResultDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ErrorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool EsExitosoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Error {
            get {
                return this.ErrorField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorField, value) != true)) {
                    this.ErrorField = value;
                    this.RaisePropertyChanged("Error");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool EsExitoso {
            get {
                return this.EsExitosoField;
            }
            set {
                if ((this.EsExitosoField.Equals(value) != true)) {
                    this.EsExitosoField = value;
                    this.RaisePropertyChanged("EsExitoso");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="FilaServicio.IFilaServicio")]
    public interface IFilaServicio {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFilaServicio/ObtenerIdFila", ReplyAction="http://tempuri.org/IFilaServicio/ObtenerIdFilaResponse")]
        int ObtenerIdFila(int idSala, int numeroFila);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFilaServicio/ObtenerIdFila", ReplyAction="http://tempuri.org/IFilaServicio/ObtenerIdFilaResponse")]
        System.Threading.Tasks.Task<int> ObtenerIdFilaAsync(int idSala, int numeroFila);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFilaServicio/AgregarFila", ReplyAction="http://tempuri.org/IFilaServicio/AgregarFilaResponse")]
        string AgregarFila(CineVerCliente.FilaServicio.FilaDTO fila);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFilaServicio/AgregarFila", ReplyAction="http://tempuri.org/IFilaServicio/AgregarFilaResponse")]
        System.Threading.Tasks.Task<string> AgregarFilaAsync(CineVerCliente.FilaServicio.FilaDTO fila);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFilaServicio/EditarFila", ReplyAction="http://tempuri.org/IFilaServicio/EditarFilaResponse")]
        string EditarFila(CineVerCliente.FilaServicio.FilaDTO filaEditada, CineVerCliente.FilaServicio.FilaDTO filaOriginal);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFilaServicio/EditarFila", ReplyAction="http://tempuri.org/IFilaServicio/EditarFilaResponse")]
        System.Threading.Tasks.Task<string> EditarFilaAsync(CineVerCliente.FilaServicio.FilaDTO filaEditada, CineVerCliente.FilaServicio.FilaDTO filaOriginal);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFilaServicio/EliminarFila", ReplyAction="http://tempuri.org/IFilaServicio/EliminarFilaResponse")]
        string EliminarFila(CineVerCliente.FilaServicio.FilaDTO fila);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFilaServicio/EliminarFila", ReplyAction="http://tempuri.org/IFilaServicio/EliminarFilaResponse")]
        System.Threading.Tasks.Task<string> EliminarFilaAsync(CineVerCliente.FilaServicio.FilaDTO fila);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFilaServicio/ObtenerFilasDeSala", ReplyAction="http://tempuri.org/IFilaServicio/ObtenerFilasDeSalaResponse")]
        CineVerCliente.FilaServicio.ListaFilasDTO ObtenerFilasDeSala(int idSala);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFilaServicio/ObtenerFilasDeSala", ReplyAction="http://tempuri.org/IFilaServicio/ObtenerFilasDeSalaResponse")]
        System.Threading.Tasks.Task<CineVerCliente.FilaServicio.ListaFilasDTO> ObtenerFilasDeSalaAsync(int idSala);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IFilaServicioChannel : CineVerCliente.FilaServicio.IFilaServicio, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class FilaServicioClient : System.ServiceModel.ClientBase<CineVerCliente.FilaServicio.IFilaServicio>, CineVerCliente.FilaServicio.IFilaServicio {
        
        public FilaServicioClient() {
        }
        
        public FilaServicioClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public FilaServicioClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FilaServicioClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FilaServicioClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int ObtenerIdFila(int idSala, int numeroFila) {
            return base.Channel.ObtenerIdFila(idSala, numeroFila);
        }
        
        public System.Threading.Tasks.Task<int> ObtenerIdFilaAsync(int idSala, int numeroFila) {
            return base.Channel.ObtenerIdFilaAsync(idSala, numeroFila);
        }
        
        public string AgregarFila(CineVerCliente.FilaServicio.FilaDTO fila) {
            return base.Channel.AgregarFila(fila);
        }
        
        public System.Threading.Tasks.Task<string> AgregarFilaAsync(CineVerCliente.FilaServicio.FilaDTO fila) {
            return base.Channel.AgregarFilaAsync(fila);
        }
        
        public string EditarFila(CineVerCliente.FilaServicio.FilaDTO filaEditada, CineVerCliente.FilaServicio.FilaDTO filaOriginal) {
            return base.Channel.EditarFila(filaEditada, filaOriginal);
        }
        
        public System.Threading.Tasks.Task<string> EditarFilaAsync(CineVerCliente.FilaServicio.FilaDTO filaEditada, CineVerCliente.FilaServicio.FilaDTO filaOriginal) {
            return base.Channel.EditarFilaAsync(filaEditada, filaOriginal);
        }
        
        public string EliminarFila(CineVerCliente.FilaServicio.FilaDTO fila) {
            return base.Channel.EliminarFila(fila);
        }
        
        public System.Threading.Tasks.Task<string> EliminarFilaAsync(CineVerCliente.FilaServicio.FilaDTO fila) {
            return base.Channel.EliminarFilaAsync(fila);
        }
        
        public CineVerCliente.FilaServicio.ListaFilasDTO ObtenerFilasDeSala(int idSala) {
            return base.Channel.ObtenerFilasDeSala(idSala);
        }
        
        public System.Threading.Tasks.Task<CineVerCliente.FilaServicio.ListaFilasDTO> ObtenerFilasDeSalaAsync(int idSala) {
            return base.Channel.ObtenerFilasDeSalaAsync(idSala);
        }
    }
}
