//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CineVerEntidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class ActorEnPelicula
    {
        public Nullable<int> idPelicula { get; set; }
        public Nullable<int> idActor { get; set; }
        public int idActorEnPelicula { get; set; }
    
        public virtual Actor Actor { get; set; }
        public virtual Película Película { get; set; }
    }
}
