//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CineVerEntidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class AsientoFuncion
    {
        public int idAsientoFuncion { get; set; }
        public int idFuncion { get; set; }
        public int idAsiento { get; set; }
        public string estado { get; set; }
    
        public virtual Asiento Asiento { get; set; }
        public virtual Función Función { get; set; }
    }
}
