//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CineVerEntidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class Boleto
    {
        public int idBoleto { get; set; }
        public Nullable<int> idFuncion { get; set; }
        public Nullable<int> idAsiento { get; set; }
        public Nullable<int> idVenta { get; set; }
    
        public virtual Asiento Asiento { get; set; }
        public virtual Función Función { get; set; }
        public virtual Venta Venta { get; set; }
    }
}
