//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CineVerEntidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class CorteCaja
    {
        public int idCorteCaja { get; set; }
        public Nullable<int> idSucursal { get; set; }
        public Nullable<decimal> efectivoEsperado { get; set; }
        public Nullable<decimal> efectivoCaja { get; set; }
        public Nullable<decimal> diferenciaEfectivo { get; set; }
        public Nullable<decimal> ventaTotal { get; set; }
        public Nullable<decimal> gastos { get; set; }
        public Nullable<decimal> ganancias { get; set; }
        public Nullable<decimal> inicioDia { get; set; }
        public Nullable<System.DateTime> fechaCorte { get; set; }
    
        public virtual Sucursal Sucursal { get; set; }
    }
}
