//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CineVerEntidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class CuentaFidelidad
    {
        public int idCuenta { get; set; }
        public Nullable<int> idSocio { get; set; }
        public Nullable<decimal> puntos { get; set; }
    
        public virtual Socio Socio { get; set; }
    }
}
