//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CineVerEntidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class Empleado
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Empleado()
        {
            this.Gasto = new HashSet<Gasto>();
            this.Venta = new HashSet<Venta>();
        }
    
        public int idEmpleado { get; set; }
        public string nombre { get; set; }
        public string apellido { get; set; }
        public string nss { get; set; }
        public string rol { get; set; }
        public Nullable<System.DateTime> fechaDeNacimiento { get; set; }
        public string sexo { get; set; }
        public string numeroTelefono { get; set; }
        public string correoElectronico { get; set; }
        public string calle { get; set; }
        public string numeroDeCasa { get; set; }
        public string codigoPostal { get; set; }
        public string rfc { get; set; }
        public string matriculaEmpleado { get; set; }
        public Nullable<int> idSucursal { get; set; }
        public byte[] foto { get; set; }
        public Nullable<bool> contratado { get; set; }
    
        public virtual Sucursal Sucursal { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Gasto> Gasto { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Venta> Venta { get; set; }
    }
}
