//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CineVerEntidades
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CineVerEntities : DbContext
    {
        public CineVerEntities()
            : base("name=CineVerEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Actor> Actor { get; set; }
        public virtual DbSet<ActorEnPelicula> ActorEnPelicula { get; set; }
        public virtual DbSet<Asiento> Asiento { get; set; }
        public virtual DbSet<Boleto> Boleto { get; set; }
        public virtual DbSet<CorteCaja> CorteCaja { get; set; }
        public virtual DbSet<CuentaFidelidad> CuentaFidelidad { get; set; }
        public virtual DbSet<Empleado> Empleado { get; set; }
        public virtual DbSet<Fila> Fila { get; set; }
        public virtual DbSet<Función> Función { get; set; }
        public virtual DbSet<Gasto> Gasto { get; set; }
        public virtual DbSet<Película> Película { get; set; }
        public virtual DbSet<ProductoDulceria> ProductoDulceria { get; set; }
        public virtual DbSet<Promocion> Promocion { get; set; }
        public virtual DbSet<Sala> Sala { get; set; }
        public virtual DbSet<Socio> Socio { get; set; }
        public virtual DbSet<Sucursal> Sucursal { get; set; }
        public virtual DbSet<Venta> Venta { get; set; }
        public virtual DbSet<VentaEnDulceria> VentaEnDulceria { get; set; }
    }
}
