//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CineVerEntidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class Película
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Película()
        {
            this.ActorEnPelicula = new HashSet<ActorEnPelicula>();
            this.Función = new HashSet<Función>();
        }
    
        public int idPelicula { get; set; }
        public string genero { get; set; }
        public Nullable<System.TimeSpan> duracion { get; set; }
        public string sinopsis { get; set; }
        public string director { get; set; }
        public Nullable<int> idSucursal { get; set; }
        public string nombre { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ActorEnPelicula> ActorEnPelicula { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Función> Función { get; set; }
        public virtual Sucursal Sucursal { get; set; }
    }
}
