//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CineVerEntidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductoDulceria
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ProductoDulceria()
        {
            this.VentaEnDulceria = new HashSet<VentaEnDulceria>();
        }
    
        public int idProducto { get; set; }
        public string nombre { get; set; }
        public Nullable<int> cantidadInventario { get; set; }
        public Nullable<decimal> costoUnitario { get; set; }
        public Nullable<decimal> precioVenta { get; set; }
        public byte[] imagen { get; set; }
        public Nullable<int> idSucursal { get; set; }
    
        public virtual Sucursal Sucursal { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VentaEnDulceria> VentaEnDulceria { get; set; }
    }
}
