//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CineVerEntidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class Promocion
    {
        public int idPromocion { get; set; }
        public string tipo { get; set; }
        public Nullable<int> idSucursal { get; set; }
        public string producto { get; set; }
        public Nullable<int> numeroProductosNecesarios { get; set; }
        public Nullable<int> numeroProductosPagar { get; set; }
        public Nullable<bool> lunesAplica { get; set; }
        public Nullable<bool> martesAplica { get; set; }
        public Nullable<bool> miercolesAplica { get; set; }
        public Nullable<bool> juevesAplica { get; set; }
        public Nullable<bool> viernesAplica { get; set; }
        public Nullable<bool> sabadoAplica { get; set; }
        public Nullable<bool> domingoAplica { get; set; }
        public string nombre { get; set; }
    
        public virtual Sucursal Sucursal { get; set; }
    }
}
