//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CineVerEntidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class Socio
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Socio()
        {
            this.CuentaFidelidad = new HashSet<CuentaFidelidad>();
            this.Venta = new HashSet<Venta>();
        }
    
        public int idSocio { get; set; }
        public string folio { get; set; }
        public string nombre { get; set; }
        public string apellido { get; set; }
        public Nullable<System.DateTime> fechaNacimiento { get; set; }
        public string sexo { get; set; }
        public string numeroTelefono { get; set; }
        public string correoElectronico { get; set; }
        public string calle { get; set; }
        public string numeroCasa { get; set; }
        public string codigoPostal { get; set; }
        public Nullable<bool> afiliado { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CuentaFidelidad> CuentaFidelidad { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Venta> Venta { get; set; }
    }
}
