//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CineVerEntidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class Venta
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Venta()
        {
            this.Boleto = new HashSet<Boleto>();
        }
    
        public int idVenta { get; set; }
        public Nullable<int> idEmpleado { get; set; }
        public Nullable<int> idSocio { get; set; }
        public Nullable<int> idSucursal { get; set; }
        public Nullable<decimal> total { get; set; }
        public string metodoPago { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public string tipoVenta { get; set; }
        public string folioVenta { get; set; }
        public Nullable<int> idFuncion { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Boleto> Boleto { get; set; }
        public virtual Empleado Empleado { get; set; }
        public virtual Socio Socio { get; set; }
        public virtual Sucursal Sucursal { get; set; }
    }
}
