//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CineVerCliente.SocioServicio {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SocioDTO", Namespace="http://schemas.datacontract.org/2004/07/CineVerServicios.DTO")]
    [System.SerializableAttribute()]
    public partial class SocioDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ApellidosField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CalleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodigoPostalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CorreoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FechaNacimientoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FolioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdSocioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombresField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NumeroCasaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NumeroTelefonoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SexoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Apellidos {
            get {
                return this.ApellidosField;
            }
            set {
                if ((object.ReferenceEquals(this.ApellidosField, value) != true)) {
                    this.ApellidosField = value;
                    this.RaisePropertyChanged("Apellidos");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Calle {
            get {
                return this.CalleField;
            }
            set {
                if ((object.ReferenceEquals(this.CalleField, value) != true)) {
                    this.CalleField = value;
                    this.RaisePropertyChanged("Calle");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodigoPostal {
            get {
                return this.CodigoPostalField;
            }
            set {
                if ((object.ReferenceEquals(this.CodigoPostalField, value) != true)) {
                    this.CodigoPostalField = value;
                    this.RaisePropertyChanged("CodigoPostal");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Correo {
            get {
                return this.CorreoField;
            }
            set {
                if ((object.ReferenceEquals(this.CorreoField, value) != true)) {
                    this.CorreoField = value;
                    this.RaisePropertyChanged("Correo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FechaNacimiento {
            get {
                return this.FechaNacimientoField;
            }
            set {
                if ((this.FechaNacimientoField.Equals(value) != true)) {
                    this.FechaNacimientoField = value;
                    this.RaisePropertyChanged("FechaNacimiento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Folio {
            get {
                return this.FolioField;
            }
            set {
                if ((object.ReferenceEquals(this.FolioField, value) != true)) {
                    this.FolioField = value;
                    this.RaisePropertyChanged("Folio");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdSocio {
            get {
                return this.IdSocioField;
            }
            set {
                if ((this.IdSocioField.Equals(value) != true)) {
                    this.IdSocioField = value;
                    this.RaisePropertyChanged("IdSocio");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombres {
            get {
                return this.NombresField;
            }
            set {
                if ((object.ReferenceEquals(this.NombresField, value) != true)) {
                    this.NombresField = value;
                    this.RaisePropertyChanged("Nombres");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NumeroCasa {
            get {
                return this.NumeroCasaField;
            }
            set {
                if ((object.ReferenceEquals(this.NumeroCasaField, value) != true)) {
                    this.NumeroCasaField = value;
                    this.RaisePropertyChanged("NumeroCasa");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NumeroTelefono {
            get {
                return this.NumeroTelefonoField;
            }
            set {
                if ((object.ReferenceEquals(this.NumeroTelefonoField, value) != true)) {
                    this.NumeroTelefonoField = value;
                    this.RaisePropertyChanged("NumeroTelefono");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Sexo {
            get {
                return this.SexoField;
            }
            set {
                if ((object.ReferenceEquals(this.SexoField, value) != true)) {
                    this.SexoField = value;
                    this.RaisePropertyChanged("Sexo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResultDTO", Namespace="http://schemas.datacontract.org/2004/07/CineVerServicios.DTO")]
    [System.SerializableAttribute()]
    public partial class ResultDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ErrorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool EsExitosoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Error {
            get {
                return this.ErrorField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorField, value) != true)) {
                    this.ErrorField = value;
                    this.RaisePropertyChanged("Error");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool EsExitoso {
            get {
                return this.EsExitosoField;
            }
            set {
                if ((this.EsExitosoField.Equals(value) != true)) {
                    this.EsExitosoField = value;
                    this.RaisePropertyChanged("EsExitoso");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ListaSociosDTO", Namespace="http://schemas.datacontract.org/2004/07/CineVerServicios.DTO")]
    [System.SerializableAttribute()]
    public partial class ListaSociosDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private CineVerCliente.SocioServicio.ResultDTO ResultField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private CineVerCliente.SocioServicio.SocioDTO[] SociosField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CineVerCliente.SocioServicio.ResultDTO Result {
            get {
                return this.ResultField;
            }
            set {
                if ((object.ReferenceEquals(this.ResultField, value) != true)) {
                    this.ResultField = value;
                    this.RaisePropertyChanged("Result");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CineVerCliente.SocioServicio.SocioDTO[] Socios {
            get {
                return this.SociosField;
            }
            set {
                if ((object.ReferenceEquals(this.SociosField, value) != true)) {
                    this.SociosField = value;
                    this.RaisePropertyChanged("Socios");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SocioResponseDTO", Namespace="http://schemas.datacontract.org/2004/07/CineVerServicios.DTO")]
    [System.SerializableAttribute()]
    public partial class SocioResponseDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private CineVerCliente.SocioServicio.ResultDTO ResultDTOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private CineVerCliente.SocioServicio.SocioDTO socioField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CineVerCliente.SocioServicio.ResultDTO ResultDTO {
            get {
                return this.ResultDTOField;
            }
            set {
                if ((object.ReferenceEquals(this.ResultDTOField, value) != true)) {
                    this.ResultDTOField = value;
                    this.RaisePropertyChanged("ResultDTO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CineVerCliente.SocioServicio.SocioDTO socio {
            get {
                return this.socioField;
            }
            set {
                if ((object.ReferenceEquals(this.socioField, value) != true)) {
                    this.socioField = value;
                    this.RaisePropertyChanged("socio");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SocioServicio.ISocioServicio")]
    public interface ISocioServicio {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISocioServicio/RegistrarSocio", ReplyAction="http://tempuri.org/ISocioServicio/RegistrarSocioResponse")]
        CineVerCliente.SocioServicio.ResultDTO RegistrarSocio(CineVerCliente.SocioServicio.SocioDTO socioDTO);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISocioServicio/RegistrarSocio", ReplyAction="http://tempuri.org/ISocioServicio/RegistrarSocioResponse")]
        System.Threading.Tasks.Task<CineVerCliente.SocioServicio.ResultDTO> RegistrarSocioAsync(CineVerCliente.SocioServicio.SocioDTO socioDTO);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISocioServicio/ModificarSocio", ReplyAction="http://tempuri.org/ISocioServicio/ModificarSocioResponse")]
        CineVerCliente.SocioServicio.ResultDTO ModificarSocio(CineVerCliente.SocioServicio.SocioDTO socioDTO);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISocioServicio/ModificarSocio", ReplyAction="http://tempuri.org/ISocioServicio/ModificarSocioResponse")]
        System.Threading.Tasks.Task<CineVerCliente.SocioServicio.ResultDTO> ModificarSocioAsync(CineVerCliente.SocioServicio.SocioDTO socioDTO);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISocioServicio/InhabilitarCuentaSocio", ReplyAction="http://tempuri.org/ISocioServicio/InhabilitarCuentaSocioResponse")]
        CineVerCliente.SocioServicio.ResultDTO InhabilitarCuentaSocio(int idSocio);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISocioServicio/InhabilitarCuentaSocio", ReplyAction="http://tempuri.org/ISocioServicio/InhabilitarCuentaSocioResponse")]
        System.Threading.Tasks.Task<CineVerCliente.SocioServicio.ResultDTO> InhabilitarCuentaSocioAsync(int idSocio);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISocioServicio/ObtenerSocios", ReplyAction="http://tempuri.org/ISocioServicio/ObtenerSociosResponse")]
        CineVerCliente.SocioServicio.ListaSociosDTO ObtenerSocios();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISocioServicio/ObtenerSocios", ReplyAction="http://tempuri.org/ISocioServicio/ObtenerSociosResponse")]
        System.Threading.Tasks.Task<CineVerCliente.SocioServicio.ListaSociosDTO> ObtenerSociosAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISocioServicio/BuscarSocioPorFolio", ReplyAction="http://tempuri.org/ISocioServicio/BuscarSocioPorFolioResponse")]
        CineVerCliente.SocioServicio.SocioResponseDTO BuscarSocioPorFolio(string folio);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISocioServicio/BuscarSocioPorFolio", ReplyAction="http://tempuri.org/ISocioServicio/BuscarSocioPorFolioResponse")]
        System.Threading.Tasks.Task<CineVerCliente.SocioServicio.SocioResponseDTO> BuscarSocioPorFolioAsync(string folio);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISocioServicio/ExisteSocio", ReplyAction="http://tempuri.org/ISocioServicio/ExisteSocioResponse")]
        CineVerCliente.SocioServicio.ResultDTO ExisteSocio(string folio);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISocioServicio/ExisteSocio", ReplyAction="http://tempuri.org/ISocioServicio/ExisteSocioResponse")]
        System.Threading.Tasks.Task<CineVerCliente.SocioServicio.ResultDTO> ExisteSocioAsync(string folio);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISocioServicioChannel : CineVerCliente.SocioServicio.ISocioServicio, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SocioServicioClient : System.ServiceModel.ClientBase<CineVerCliente.SocioServicio.ISocioServicio>, CineVerCliente.SocioServicio.ISocioServicio {
        
        public SocioServicioClient() {
        }
        
        public SocioServicioClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SocioServicioClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SocioServicioClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SocioServicioClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public CineVerCliente.SocioServicio.ResultDTO RegistrarSocio(CineVerCliente.SocioServicio.SocioDTO socioDTO) {
            return base.Channel.RegistrarSocio(socioDTO);
        }
        
        public System.Threading.Tasks.Task<CineVerCliente.SocioServicio.ResultDTO> RegistrarSocioAsync(CineVerCliente.SocioServicio.SocioDTO socioDTO) {
            return base.Channel.RegistrarSocioAsync(socioDTO);
        }
        
        public CineVerCliente.SocioServicio.ResultDTO ModificarSocio(CineVerCliente.SocioServicio.SocioDTO socioDTO) {
            return base.Channel.ModificarSocio(socioDTO);
        }
        
        public System.Threading.Tasks.Task<CineVerCliente.SocioServicio.ResultDTO> ModificarSocioAsync(CineVerCliente.SocioServicio.SocioDTO socioDTO) {
            return base.Channel.ModificarSocioAsync(socioDTO);
        }
        
        public CineVerCliente.SocioServicio.ResultDTO InhabilitarCuentaSocio(int idSocio) {
            return base.Channel.InhabilitarCuentaSocio(idSocio);
        }
        
        public System.Threading.Tasks.Task<CineVerCliente.SocioServicio.ResultDTO> InhabilitarCuentaSocioAsync(int idSocio) {
            return base.Channel.InhabilitarCuentaSocioAsync(idSocio);
        }
        
        public CineVerCliente.SocioServicio.ListaSociosDTO ObtenerSocios() {
            return base.Channel.ObtenerSocios();
        }
        
        public System.Threading.Tasks.Task<CineVerCliente.SocioServicio.ListaSociosDTO> ObtenerSociosAsync() {
            return base.Channel.ObtenerSociosAsync();
        }
        
        public CineVerCliente.SocioServicio.SocioResponseDTO BuscarSocioPorFolio(string folio) {
            return base.Channel.BuscarSocioPorFolio(folio);
        }
        
        public System.Threading.Tasks.Task<CineVerCliente.SocioServicio.SocioResponseDTO> BuscarSocioPorFolioAsync(string folio) {
            return base.Channel.BuscarSocioPorFolioAsync(folio);
        }
        
        public CineVerCliente.SocioServicio.ResultDTO ExisteSocio(string folio) {
            return base.Channel.ExisteSocio(folio);
        }
        
        public System.Threading.Tasks.Task<CineVerCliente.SocioServicio.ResultDTO> ExisteSocioAsync(string folio) {
            return base.Channel.ExisteSocioAsync(folio);
        }
    }
}
