//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CineVerCliente.SalaServicio {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ListaSalaDTO", Namespace="http://schemas.datacontract.org/2004/07/CineVerServicios.DTO")]
    [System.SerializableAttribute()]
    public partial class ListaSalaDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private CineVerCliente.SalaServicio.ResultDTO ResultField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private CineVerCliente.SalaServicio.SalaDTO[] SalasField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CineVerCliente.SalaServicio.ResultDTO Result {
            get {
                return this.ResultField;
            }
            set {
                if ((object.ReferenceEquals(this.ResultField, value) != true)) {
                    this.ResultField = value;
                    this.RaisePropertyChanged("Result");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CineVerCliente.SalaServicio.SalaDTO[] Salas {
            get {
                return this.SalasField;
            }
            set {
                if ((object.ReferenceEquals(this.SalasField, value) != true)) {
                    this.SalasField = value;
                    this.RaisePropertyChanged("Salas");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResultDTO", Namespace="http://schemas.datacontract.org/2004/07/CineVerServicios.DTO")]
    [System.SerializableAttribute()]
    public partial class ResultDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ErrorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool EsExitosoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Error {
            get {
                return this.ErrorField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorField, value) != true)) {
                    this.ErrorField = value;
                    this.RaisePropertyChanged("Error");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool EsExitoso {
            get {
                return this.EsExitosoField;
            }
            set {
                if ((this.EsExitosoField.Equals(value) != true)) {
                    this.EsExitosoField = value;
                    this.RaisePropertyChanged("EsExitoso");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SalaDTO", Namespace="http://schemas.datacontract.org/2004/07/CineVerServicios.DTO")]
    [System.SerializableAttribute()]
    public partial class SalaDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string descripcionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string estadoSalaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idSalaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> idSucursalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> numeroFilasField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string descripcion {
            get {
                return this.descripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.descripcionField, value) != true)) {
                    this.descripcionField = value;
                    this.RaisePropertyChanged("descripcion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string estadoSala {
            get {
                return this.estadoSalaField;
            }
            set {
                if ((object.ReferenceEquals(this.estadoSalaField, value) != true)) {
                    this.estadoSalaField = value;
                    this.RaisePropertyChanged("estadoSala");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idSala {
            get {
                return this.idSalaField;
            }
            set {
                if ((this.idSalaField.Equals(value) != true)) {
                    this.idSalaField = value;
                    this.RaisePropertyChanged("idSala");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> idSucursal {
            get {
                return this.idSucursalField;
            }
            set {
                if ((this.idSucursalField.Equals(value) != true)) {
                    this.idSucursalField = value;
                    this.RaisePropertyChanged("idSucursal");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                if ((object.ReferenceEquals(this.nombreField, value) != true)) {
                    this.nombreField = value;
                    this.RaisePropertyChanged("nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> numeroFilas {
            get {
                return this.numeroFilasField;
            }
            set {
                if ((this.numeroFilasField.Equals(value) != true)) {
                    this.numeroFilasField = value;
                    this.RaisePropertyChanged("numeroFilas");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SalaServicio.ISalaServicio")]
    public interface ISalaServicio {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISalaServicio/ObtenerSalasPorSucursal", ReplyAction="http://tempuri.org/ISalaServicio/ObtenerSalasPorSucursalResponse")]
        CineVerCliente.SalaServicio.ListaSalaDTO ObtenerSalasPorSucursal(int idSucursal);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISalaServicio/ObtenerSalasPorSucursal", ReplyAction="http://tempuri.org/ISalaServicio/ObtenerSalasPorSucursalResponse")]
        System.Threading.Tasks.Task<CineVerCliente.SalaServicio.ListaSalaDTO> ObtenerSalasPorSucursalAsync(int idSucursal);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISalaServicio/AgregarSala", ReplyAction="http://tempuri.org/ISalaServicio/AgregarSalaResponse")]
        string AgregarSala(CineVerCliente.SalaServicio.SalaDTO sala);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISalaServicio/AgregarSala", ReplyAction="http://tempuri.org/ISalaServicio/AgregarSalaResponse")]
        System.Threading.Tasks.Task<string> AgregarSalaAsync(CineVerCliente.SalaServicio.SalaDTO sala);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISalaServicio/EditarSala", ReplyAction="http://tempuri.org/ISalaServicio/EditarSalaResponse")]
        string EditarSala(CineVerCliente.SalaServicio.SalaDTO salaEditada, CineVerCliente.SalaServicio.SalaDTO salaOriginal);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISalaServicio/EditarSala", ReplyAction="http://tempuri.org/ISalaServicio/EditarSalaResponse")]
        System.Threading.Tasks.Task<string> EditarSalaAsync(CineVerCliente.SalaServicio.SalaDTO salaEditada, CineVerCliente.SalaServicio.SalaDTO salaOriginal);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISalaServicio/EliminarSala", ReplyAction="http://tempuri.org/ISalaServicio/EliminarSalaResponse")]
        string EliminarSala(CineVerCliente.SalaServicio.SalaDTO sala);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISalaServicio/EliminarSala", ReplyAction="http://tempuri.org/ISalaServicio/EliminarSalaResponse")]
        System.Threading.Tasks.Task<string> EliminarSalaAsync(CineVerCliente.SalaServicio.SalaDTO sala);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISalaServicio/ObtenerIdSala", ReplyAction="http://tempuri.org/ISalaServicio/ObtenerIdSalaResponse")]
        int ObtenerIdSala(int idSucursal, string nombre);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISalaServicio/ObtenerIdSala", ReplyAction="http://tempuri.org/ISalaServicio/ObtenerIdSalaResponse")]
        System.Threading.Tasks.Task<int> ObtenerIdSalaAsync(int idSucursal, string nombre);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISalaServicio/ObtenerSalasPorSucursalYNombre", ReplyAction="http://tempuri.org/ISalaServicio/ObtenerSalasPorSucursalYNombreResponse")]
        CineVerCliente.SalaServicio.ListaSalaDTO ObtenerSalasPorSucursalYNombre(int idSucursal, string nombre);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISalaServicio/ObtenerSalasPorSucursalYNombre", ReplyAction="http://tempuri.org/ISalaServicio/ObtenerSalasPorSucursalYNombreResponse")]
        System.Threading.Tasks.Task<CineVerCliente.SalaServicio.ListaSalaDTO> ObtenerSalasPorSucursalYNombreAsync(int idSucursal, string nombre);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISalaServicioChannel : CineVerCliente.SalaServicio.ISalaServicio, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SalaServicioClient : System.ServiceModel.ClientBase<CineVerCliente.SalaServicio.ISalaServicio>, CineVerCliente.SalaServicio.ISalaServicio {
        
        public SalaServicioClient() {
        }
        
        public SalaServicioClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SalaServicioClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SalaServicioClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SalaServicioClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public CineVerCliente.SalaServicio.ListaSalaDTO ObtenerSalasPorSucursal(int idSucursal) {
            return base.Channel.ObtenerSalasPorSucursal(idSucursal);
        }
        
        public System.Threading.Tasks.Task<CineVerCliente.SalaServicio.ListaSalaDTO> ObtenerSalasPorSucursalAsync(int idSucursal) {
            return base.Channel.ObtenerSalasPorSucursalAsync(idSucursal);
        }
        
        public string AgregarSala(CineVerCliente.SalaServicio.SalaDTO sala) {
            return base.Channel.AgregarSala(sala);
        }
        
        public System.Threading.Tasks.Task<string> AgregarSalaAsync(CineVerCliente.SalaServicio.SalaDTO sala) {
            return base.Channel.AgregarSalaAsync(sala);
        }
        
        public string EditarSala(CineVerCliente.SalaServicio.SalaDTO salaEditada, CineVerCliente.SalaServicio.SalaDTO salaOriginal) {
            return base.Channel.EditarSala(salaEditada, salaOriginal);
        }
        
        public System.Threading.Tasks.Task<string> EditarSalaAsync(CineVerCliente.SalaServicio.SalaDTO salaEditada, CineVerCliente.SalaServicio.SalaDTO salaOriginal) {
            return base.Channel.EditarSalaAsync(salaEditada, salaOriginal);
        }
        
        public string EliminarSala(CineVerCliente.SalaServicio.SalaDTO sala) {
            return base.Channel.EliminarSala(sala);
        }
        
        public System.Threading.Tasks.Task<string> EliminarSalaAsync(CineVerCliente.SalaServicio.SalaDTO sala) {
            return base.Channel.EliminarSalaAsync(sala);
        }
        
        public int ObtenerIdSala(int idSucursal, string nombre) {
            return base.Channel.ObtenerIdSala(idSucursal, nombre);
        }
        
        public System.Threading.Tasks.Task<int> ObtenerIdSalaAsync(int idSucursal, string nombre) {
            return base.Channel.ObtenerIdSalaAsync(idSucursal, nombre);
        }
        
        public CineVerCliente.SalaServicio.ListaSalaDTO ObtenerSalasPorSucursalYNombre(int idSucursal, string nombre) {
            return base.Channel.ObtenerSalasPorSucursalYNombre(idSucursal, nombre);
        }
        
        public System.Threading.Tasks.Task<CineVerCliente.SalaServicio.ListaSalaDTO> ObtenerSalasPorSucursalYNombreAsync(int idSucursal, string nombre) {
            return base.Channel.ObtenerSalasPorSucursalYNombreAsync(idSucursal, nombre);
        }
    }
}
