//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CineVerCliente.AsientoServicio {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AsientoDTO", Namespace="http://schemas.datacontract.org/2004/07/CineVerServicios.DTO")]
    [System.SerializableAttribute()]
    public partial class AsientoDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string estadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idAsientoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> idFilaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string letraColumnaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string estado {
            get {
                return this.estadoField;
            }
            set {
                if ((object.ReferenceEquals(this.estadoField, value) != true)) {
                    this.estadoField = value;
                    this.RaisePropertyChanged("estado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idAsiento {
            get {
                return this.idAsientoField;
            }
            set {
                if ((this.idAsientoField.Equals(value) != true)) {
                    this.idAsientoField = value;
                    this.RaisePropertyChanged("idAsiento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> idFila {
            get {
                return this.idFilaField;
            }
            set {
                if ((this.idFilaField.Equals(value) != true)) {
                    this.idFilaField = value;
                    this.RaisePropertyChanged("idFila");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string letraColumna {
            get {
                return this.letraColumnaField;
            }
            set {
                if ((object.ReferenceEquals(this.letraColumnaField, value) != true)) {
                    this.letraColumnaField = value;
                    this.RaisePropertyChanged("letraColumna");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ListaAsientosDTO", Namespace="http://schemas.datacontract.org/2004/07/CineVerServicios.DTO")]
    [System.SerializableAttribute()]
    public partial class ListaAsientosDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private CineVerCliente.AsientoServicio.AsientoDTO[] AsientosField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private CineVerCliente.AsientoServicio.ResultDTO ResultField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CineVerCliente.AsientoServicio.AsientoDTO[] Asientos {
            get {
                return this.AsientosField;
            }
            set {
                if ((object.ReferenceEquals(this.AsientosField, value) != true)) {
                    this.AsientosField = value;
                    this.RaisePropertyChanged("Asientos");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CineVerCliente.AsientoServicio.ResultDTO Result {
            get {
                return this.ResultField;
            }
            set {
                if ((object.ReferenceEquals(this.ResultField, value) != true)) {
                    this.ResultField = value;
                    this.RaisePropertyChanged("Result");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResultDTO", Namespace="http://schemas.datacontract.org/2004/07/CineVerServicios.DTO")]
    [System.SerializableAttribute()]
    public partial class ResultDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ErrorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool EsExitosoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Error {
            get {
                return this.ErrorField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorField, value) != true)) {
                    this.ErrorField = value;
                    this.RaisePropertyChanged("Error");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool EsExitoso {
            get {
                return this.EsExitosoField;
            }
            set {
                if ((this.EsExitosoField.Equals(value) != true)) {
                    this.EsExitosoField = value;
                    this.RaisePropertyChanged("EsExitoso");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="AsientoServicio.IAsientoServicio")]
    public interface IAsientoServicio {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAsientoServicio/AgregarAsiento", ReplyAction="http://tempuri.org/IAsientoServicio/AgregarAsientoResponse")]
        string AgregarAsiento(CineVerCliente.AsientoServicio.AsientoDTO asientoDTO);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAsientoServicio/AgregarAsiento", ReplyAction="http://tempuri.org/IAsientoServicio/AgregarAsientoResponse")]
        System.Threading.Tasks.Task<string> AgregarAsientoAsync(CineVerCliente.AsientoServicio.AsientoDTO asientoDTO);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAsientoServicio/EditarAsiento", ReplyAction="http://tempuri.org/IAsientoServicio/EditarAsientoResponse")]
        string EditarAsiento(CineVerCliente.AsientoServicio.AsientoDTO asientoEditado, CineVerCliente.AsientoServicio.AsientoDTO asientoOriginal);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAsientoServicio/EditarAsiento", ReplyAction="http://tempuri.org/IAsientoServicio/EditarAsientoResponse")]
        System.Threading.Tasks.Task<string> EditarAsientoAsync(CineVerCliente.AsientoServicio.AsientoDTO asientoEditado, CineVerCliente.AsientoServicio.AsientoDTO asientoOriginal);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAsientoServicio/EliminarAsiento", ReplyAction="http://tempuri.org/IAsientoServicio/EliminarAsientoResponse")]
        string EliminarAsiento(CineVerCliente.AsientoServicio.AsientoDTO asiento);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAsientoServicio/EliminarAsiento", ReplyAction="http://tempuri.org/IAsientoServicio/EliminarAsientoResponse")]
        System.Threading.Tasks.Task<string> EliminarAsientoAsync(CineVerCliente.AsientoServicio.AsientoDTO asiento);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAsientoServicio/ObtenerIdAsiento", ReplyAction="http://tempuri.org/IAsientoServicio/ObtenerIdAsientoResponse")]
        int ObtenerIdAsiento(string letraColumna, int idFila);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAsientoServicio/ObtenerIdAsiento", ReplyAction="http://tempuri.org/IAsientoServicio/ObtenerIdAsientoResponse")]
        System.Threading.Tasks.Task<int> ObtenerIdAsientoAsync(string letraColumna, int idFila);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAsientoServicio/ObtenerListaAsientosPorFila", ReplyAction="http://tempuri.org/IAsientoServicio/ObtenerListaAsientosPorFilaResponse")]
        CineVerCliente.AsientoServicio.ListaAsientosDTO ObtenerListaAsientosPorFila(int idFila);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAsientoServicio/ObtenerListaAsientosPorFila", ReplyAction="http://tempuri.org/IAsientoServicio/ObtenerListaAsientosPorFilaResponse")]
        System.Threading.Tasks.Task<CineVerCliente.AsientoServicio.ListaAsientosDTO> ObtenerListaAsientosPorFilaAsync(int idFila);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IAsientoServicioChannel : CineVerCliente.AsientoServicio.IAsientoServicio, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AsientoServicioClient : System.ServiceModel.ClientBase<CineVerCliente.AsientoServicio.IAsientoServicio>, CineVerCliente.AsientoServicio.IAsientoServicio {
        
        public AsientoServicioClient() {
        }
        
        public AsientoServicioClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AsientoServicioClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AsientoServicioClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AsientoServicioClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string AgregarAsiento(CineVerCliente.AsientoServicio.AsientoDTO asientoDTO) {
            return base.Channel.AgregarAsiento(asientoDTO);
        }
        
        public System.Threading.Tasks.Task<string> AgregarAsientoAsync(CineVerCliente.AsientoServicio.AsientoDTO asientoDTO) {
            return base.Channel.AgregarAsientoAsync(asientoDTO);
        }
        
        public string EditarAsiento(CineVerCliente.AsientoServicio.AsientoDTO asientoEditado, CineVerCliente.AsientoServicio.AsientoDTO asientoOriginal) {
            return base.Channel.EditarAsiento(asientoEditado, asientoOriginal);
        }
        
        public System.Threading.Tasks.Task<string> EditarAsientoAsync(CineVerCliente.AsientoServicio.AsientoDTO asientoEditado, CineVerCliente.AsientoServicio.AsientoDTO asientoOriginal) {
            return base.Channel.EditarAsientoAsync(asientoEditado, asientoOriginal);
        }
        
        public string EliminarAsiento(CineVerCliente.AsientoServicio.AsientoDTO asiento) {
            return base.Channel.EliminarAsiento(asiento);
        }
        
        public System.Threading.Tasks.Task<string> EliminarAsientoAsync(CineVerCliente.AsientoServicio.AsientoDTO asiento) {
            return base.Channel.EliminarAsientoAsync(asiento);
        }
        
        public int ObtenerIdAsiento(string letraColumna, int idFila) {
            return base.Channel.ObtenerIdAsiento(letraColumna, idFila);
        }
        
        public System.Threading.Tasks.Task<int> ObtenerIdAsientoAsync(string letraColumna, int idFila) {
            return base.Channel.ObtenerIdAsientoAsync(letraColumna, idFila);
        }
        
        public CineVerCliente.AsientoServicio.ListaAsientosDTO ObtenerListaAsientosPorFila(int idFila) {
            return base.Channel.ObtenerListaAsientosPorFila(idFila);
        }
        
        public System.Threading.Tasks.Task<CineVerCliente.AsientoServicio.ListaAsientosDTO> ObtenerListaAsientosPorFilaAsync(int idFila) {
            return base.Channel.ObtenerListaAsientosPorFilaAsync(idFila);
        }
    }
}
