//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CineVerCliente.DulceriaServicio {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ListaProductosDulceriaDTO", Namespace="http://schemas.datacontract.org/2004/07/CineVerServicios.DTO")]
    [System.SerializableAttribute()]
    public partial class ListaProductosDulceriaDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private CineVerCliente.DulceriaServicio.ProductoDulceriaDTO[] ProductosField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private CineVerCliente.DulceriaServicio.ResultDTO ResultDTOField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CineVerCliente.DulceriaServicio.ProductoDulceriaDTO[] Productos {
            get {
                return this.ProductosField;
            }
            set {
                if ((object.ReferenceEquals(this.ProductosField, value) != true)) {
                    this.ProductosField = value;
                    this.RaisePropertyChanged("Productos");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CineVerCliente.DulceriaServicio.ResultDTO ResultDTO {
            get {
                return this.ResultDTOField;
            }
            set {
                if ((object.ReferenceEquals(this.ResultDTOField, value) != true)) {
                    this.ResultDTOField = value;
                    this.RaisePropertyChanged("ResultDTO");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResultDTO", Namespace="http://schemas.datacontract.org/2004/07/CineVerServicios.DTO")]
    [System.SerializableAttribute()]
    public partial class ResultDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ErrorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool EsExitosoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Error {
            get {
                return this.ErrorField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorField, value) != true)) {
                    this.ErrorField = value;
                    this.RaisePropertyChanged("Error");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool EsExitoso {
            get {
                return this.EsExitosoField;
            }
            set {
                if ((this.EsExitosoField.Equals(value) != true)) {
                    this.EsExitosoField = value;
                    this.RaisePropertyChanged("EsExitoso");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ProductoDulceriaDTO", Namespace="http://schemas.datacontract.org/2004/07/CineVerServicios.DTO")]
    [System.SerializableAttribute()]
    public partial class ProductoDulceriaDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CantidadInventarioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal CostoUnitarioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdProductoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdSucursalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] ImagenField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal PrecioVentaUnitarioField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CantidadInventario {
            get {
                return this.CantidadInventarioField;
            }
            set {
                if ((this.CantidadInventarioField.Equals(value) != true)) {
                    this.CantidadInventarioField = value;
                    this.RaisePropertyChanged("CantidadInventario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal CostoUnitario {
            get {
                return this.CostoUnitarioField;
            }
            set {
                if ((this.CostoUnitarioField.Equals(value) != true)) {
                    this.CostoUnitarioField = value;
                    this.RaisePropertyChanged("CostoUnitario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdProducto {
            get {
                return this.IdProductoField;
            }
            set {
                if ((this.IdProductoField.Equals(value) != true)) {
                    this.IdProductoField = value;
                    this.RaisePropertyChanged("IdProducto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdSucursal {
            get {
                return this.IdSucursalField;
            }
            set {
                if ((this.IdSucursalField.Equals(value) != true)) {
                    this.IdSucursalField = value;
                    this.RaisePropertyChanged("IdSucursal");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] Imagen {
            get {
                return this.ImagenField;
            }
            set {
                if ((object.ReferenceEquals(this.ImagenField, value) != true)) {
                    this.ImagenField = value;
                    this.RaisePropertyChanged("Imagen");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal PrecioVentaUnitario {
            get {
                return this.PrecioVentaUnitarioField;
            }
            set {
                if ((this.PrecioVentaUnitarioField.Equals(value) != true)) {
                    this.PrecioVentaUnitarioField = value;
                    this.RaisePropertyChanged("PrecioVentaUnitario");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ProductoDulceriaResponseDTO", Namespace="http://schemas.datacontract.org/2004/07/CineVerServicios.DTO")]
    [System.SerializableAttribute()]
    public partial class ProductoDulceriaResponseDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private CineVerCliente.DulceriaServicio.ProductoDulceriaDTO ProductoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private CineVerCliente.DulceriaServicio.ResultDTO ResultDTOField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CineVerCliente.DulceriaServicio.ProductoDulceriaDTO Producto {
            get {
                return this.ProductoField;
            }
            set {
                if ((object.ReferenceEquals(this.ProductoField, value) != true)) {
                    this.ProductoField = value;
                    this.RaisePropertyChanged("Producto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CineVerCliente.DulceriaServicio.ResultDTO ResultDTO {
            get {
                return this.ResultDTOField;
            }
            set {
                if ((object.ReferenceEquals(this.ResultDTOField, value) != true)) {
                    this.ResultDTOField = value;
                    this.RaisePropertyChanged("ResultDTO");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="DulceriaServicio.IDulceriaServicio")]
    public interface IDulceriaServicio {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDulceriaServicio/ObtenerProductosDulceria", ReplyAction="http://tempuri.org/IDulceriaServicio/ObtenerProductosDulceriaResponse")]
        CineVerCliente.DulceriaServicio.ListaProductosDulceriaDTO ObtenerProductosDulceria();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDulceriaServicio/ObtenerProductosDulceria", ReplyAction="http://tempuri.org/IDulceriaServicio/ObtenerProductosDulceriaResponse")]
        System.Threading.Tasks.Task<CineVerCliente.DulceriaServicio.ListaProductosDulceriaDTO> ObtenerProductosDulceriaAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDulceriaServicio/AgregarInventario", ReplyAction="http://tempuri.org/IDulceriaServicio/AgregarInventarioResponse")]
        CineVerCliente.DulceriaServicio.ResultDTO AgregarInventario(System.Collections.Generic.Dictionary<int, int> inventario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDulceriaServicio/AgregarInventario", ReplyAction="http://tempuri.org/IDulceriaServicio/AgregarInventarioResponse")]
        System.Threading.Tasks.Task<CineVerCliente.DulceriaServicio.ResultDTO> AgregarInventarioAsync(System.Collections.Generic.Dictionary<int, int> inventario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDulceriaServicio/AgregarProductoDulceria", ReplyAction="http://tempuri.org/IDulceriaServicio/AgregarProductoDulceriaResponse")]
        CineVerCliente.DulceriaServicio.ResultDTO AgregarProductoDulceria(CineVerCliente.DulceriaServicio.ProductoDulceriaDTO producto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDulceriaServicio/AgregarProductoDulceria", ReplyAction="http://tempuri.org/IDulceriaServicio/AgregarProductoDulceriaResponse")]
        System.Threading.Tasks.Task<CineVerCliente.DulceriaServicio.ResultDTO> AgregarProductoDulceriaAsync(CineVerCliente.DulceriaServicio.ProductoDulceriaDTO producto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDulceriaServicio/ObtenerProductoDulceria", ReplyAction="http://tempuri.org/IDulceriaServicio/ObtenerProductoDulceriaResponse")]
        CineVerCliente.DulceriaServicio.ProductoDulceriaResponseDTO ObtenerProductoDulceria(int idProducto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDulceriaServicio/ObtenerProductoDulceria", ReplyAction="http://tempuri.org/IDulceriaServicio/ObtenerProductoDulceriaResponse")]
        System.Threading.Tasks.Task<CineVerCliente.DulceriaServicio.ProductoDulceriaResponseDTO> ObtenerProductoDulceriaAsync(int idProducto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDulceriaServicio/ActualizarProductoDulceria", ReplyAction="http://tempuri.org/IDulceriaServicio/ActualizarProductoDulceriaResponse")]
        CineVerCliente.DulceriaServicio.ResultDTO ActualizarProductoDulceria(CineVerCliente.DulceriaServicio.ProductoDulceriaDTO producto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDulceriaServicio/ActualizarProductoDulceria", ReplyAction="http://tempuri.org/IDulceriaServicio/ActualizarProductoDulceriaResponse")]
        System.Threading.Tasks.Task<CineVerCliente.DulceriaServicio.ResultDTO> ActualizarProductoDulceriaAsync(CineVerCliente.DulceriaServicio.ProductoDulceriaDTO producto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDulceriaServicio/ReportarMerma", ReplyAction="http://tempuri.org/IDulceriaServicio/ReportarMermaResponse")]
        CineVerCliente.DulceriaServicio.ResultDTO ReportarMerma(int idProducto, int cantidadMerma);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDulceriaServicio/ReportarMerma", ReplyAction="http://tempuri.org/IDulceriaServicio/ReportarMermaResponse")]
        System.Threading.Tasks.Task<CineVerCliente.DulceriaServicio.ResultDTO> ReportarMermaAsync(int idProducto, int cantidadMerma);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IDulceriaServicioChannel : CineVerCliente.DulceriaServicio.IDulceriaServicio, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DulceriaServicioClient : System.ServiceModel.ClientBase<CineVerCliente.DulceriaServicio.IDulceriaServicio>, CineVerCliente.DulceriaServicio.IDulceriaServicio {
        
        public DulceriaServicioClient() {
        }
        
        public DulceriaServicioClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DulceriaServicioClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DulceriaServicioClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DulceriaServicioClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public CineVerCliente.DulceriaServicio.ListaProductosDulceriaDTO ObtenerProductosDulceria() {
            return base.Channel.ObtenerProductosDulceria();
        }
        
        public System.Threading.Tasks.Task<CineVerCliente.DulceriaServicio.ListaProductosDulceriaDTO> ObtenerProductosDulceriaAsync() {
            return base.Channel.ObtenerProductosDulceriaAsync();
        }
        
        public CineVerCliente.DulceriaServicio.ResultDTO AgregarInventario(System.Collections.Generic.Dictionary<int, int> inventario) {
            return base.Channel.AgregarInventario(inventario);
        }
        
        public System.Threading.Tasks.Task<CineVerCliente.DulceriaServicio.ResultDTO> AgregarInventarioAsync(System.Collections.Generic.Dictionary<int, int> inventario) {
            return base.Channel.AgregarInventarioAsync(inventario);
        }
        
        public CineVerCliente.DulceriaServicio.ResultDTO AgregarProductoDulceria(CineVerCliente.DulceriaServicio.ProductoDulceriaDTO producto) {
            return base.Channel.AgregarProductoDulceria(producto);
        }
        
        public System.Threading.Tasks.Task<CineVerCliente.DulceriaServicio.ResultDTO> AgregarProductoDulceriaAsync(CineVerCliente.DulceriaServicio.ProductoDulceriaDTO producto) {
            return base.Channel.AgregarProductoDulceriaAsync(producto);
        }
        
        public CineVerCliente.DulceriaServicio.ProductoDulceriaResponseDTO ObtenerProductoDulceria(int idProducto) {
            return base.Channel.ObtenerProductoDulceria(idProducto);
        }
        
        public System.Threading.Tasks.Task<CineVerCliente.DulceriaServicio.ProductoDulceriaResponseDTO> ObtenerProductoDulceriaAsync(int idProducto) {
            return base.Channel.ObtenerProductoDulceriaAsync(idProducto);
        }
        
        public CineVerCliente.DulceriaServicio.ResultDTO ActualizarProductoDulceria(CineVerCliente.DulceriaServicio.ProductoDulceriaDTO producto) {
            return base.Channel.ActualizarProductoDulceria(producto);
        }
        
        public System.Threading.Tasks.Task<CineVerCliente.DulceriaServicio.ResultDTO> ActualizarProductoDulceriaAsync(CineVerCliente.DulceriaServicio.ProductoDulceriaDTO producto) {
            return base.Channel.ActualizarProductoDulceriaAsync(producto);
        }
        
        public CineVerCliente.DulceriaServicio.ResultDTO ReportarMerma(int idProducto, int cantidadMerma) {
            return base.Channel.ReportarMerma(idProducto, cantidadMerma);
        }
        
        public System.Threading.Tasks.Task<CineVerCliente.DulceriaServicio.ResultDTO> ReportarMermaAsync(int idProducto, int cantidadMerma) {
            return base.Channel.ReportarMermaAsync(idProducto, cantidadMerma);
        }
    }
}
