//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CineVerCliente.DulceriaServicio {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="DulceriaServicio.IDulceriaServicio")]
    public interface IDulceriaServicio {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDulceriaServicio/AgregarProductoDulceria", ReplyAction="http://tempuri.org/IDulceriaServicio/AgregarProductoDulceriaResponse")]
        string AgregarProductoDulceria();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDulceriaServicio/AgregarProductoDulceria", ReplyAction="http://tempuri.org/IDulceriaServicio/AgregarProductoDulceriaResponse")]
        System.Threading.Tasks.Task<string> AgregarProductoDulceriaAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IDulceriaServicioChannel : CineVerCliente.DulceriaServicio.IDulceriaServicio, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DulceriaServicioClient : System.ServiceModel.ClientBase<CineVerCliente.DulceriaServicio.IDulceriaServicio>, CineVerCliente.DulceriaServicio.IDulceriaServicio {
        
        public DulceriaServicioClient() {
        }
        
        public DulceriaServicioClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DulceriaServicioClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DulceriaServicioClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DulceriaServicioClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string AgregarProductoDulceria() {
            return base.Channel.AgregarProductoDulceria();
        }
        
        public System.Threading.Tasks.Task<string> AgregarProductoDulceriaAsync() {
            return base.Channel.AgregarProductoDulceriaAsync();
        }
    }
}
